matrix:
  include:
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
    script:
      - chmod +x ./_linux.sh
      - ./_linux.sh
  - name: "MacOS"
    os: osx
    osx_image: xcode8
    script:
      - chmod +x ./_macos.sh
      - ./_macos.sh
