language: cpp

# if: commit_message =~ /^:hammer:/

matrix:
  include:
  - name: "MacOS"
    os: osx
    compiler: clang++
    # cache:
    #   directories:
    #    - /home/travis/qt
    script:
      - chmod +x ./install-qt.sh
      - chmod +x ./extract-qt-installer.sh
      - export QT_CI_PACKAGES=qt,qt.qt5.5111,qt.qt5.5111.clang_64
      - ./install-qt.sh 5.11.1 /home/travis/qt
      - ls -la /home/travis
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
    script:
      - echo OK.
      # - wget "https://download.qt.io/archive/qt/5.11/5.11.1/qt-opensource-linux-x64-5.11.1.run"
      # - chmod +x qt-opensource-linux-x64-5.11.1.run
      # - qt-opensource-linux-x64-5.11.1.run --script qinstall.qs --silent


 
