language: cpp

compiler: clang++

matrix:
  include:
  # - name: "Linux"
  #   os: linux
  #   dist: xenial
  #   sudo: false
  #   script:
  #     - chmod +x ./_linux.sh
  #     - ./_linux.sh
  - name: "MacOS"
    os: osx
    script:
      - chmod +x ./_macos.sh
      - ./_macos.sh

deploy:
  - provider: script
    script:
      - ls
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    draft: true
    file:
      - "freeimage.dylib"
