language: cpp

if: commit_message =~ /^:hammer:/

matrix:
  include:
  - name: "MacOS"
    os: osx
    env:
      - OSXBUILD=true
    compiler: clang++
    cache:
      directories:
       - /Users/travis/qt-osx
    script:
      # - if [[ ! -d /Users/travis/qt-osx/Qt ]]; then
      #     chmod +x ./install-qt.sh;
      #     chmod +x ./extract-qt-installer.sh;
      #     export QT_CI_PACKAGES=qt.qt5.5130.clang_64;
      #     ./install-qt.sh 5.13.0 /Users/travis/qt-osx;
      #   fi;
      # - ls -la /Users/travis/qt-osx/Qt;
      # - ls -la "/Users/travis/qt-osx/Qt/Qt Creator.app/Contents/Frameworks";
      # - chmod +x ./pack-qt-osx.sh
      # - ./pack-qt-osx.sh
      - chmod +x ./fix-rpath.sh
      - ./fix-rpath.sh
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
    script:
      - echo OK.
      # - wget "https://download.qt.io/archive/qt/5.11/5.11.1/qt-opensource-linux-x64-5.11.1.run"
      # - chmod +x qt-opensource-linux-x64-5.11.1.run
      # - qt-opensource-linux-x64-5.11.1.run --script qinstall.qs --silent

deploy:
  on:
    all_branches: true
    condition: $OSXBUILD = true
  provider: releases
  name: "Binary for OSX"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  file:
    # - qpack.zip
    - libqcocoa.dylib
