# $1 is tmp path - ${{ github.workspace }}/../__tmp
# $2 is Qt platform path - /home/opc/6.8.0/gcc_arm64

rm -rf $1
mkdir -p $1
mkdir -p $1/plugins
mkdir -p $1/plugins/platforms
mkdir -p $1/plugins/iconengines
mkdir -p $1/plugins/imageformats
mkdir -p $1/plugins/qmltooling
mkdir -p $1/plugins/xcbglintegrations
mkdir -p $1/qml
mkdir -p $1/qml/QtTest
mkdir -p $1/qml/QtQuick
mkdir -p $1/qml/QtQuick/Window
mkdir -p $1/qml/QtQuick/VectorImage
mkdir -p $1/qml/QtQuick/tooling
mkdir -p $1/qml/QtQuick/Templates
mkdir -p $1/qml/QtQuick/Shapes
mkdir -p $1/qml/QtQuick/Particles
mkdir -p $1/qml/QtQuick/NativeStyle
mkdir -p $1/qml/QtQuick/NativeStyle/util
mkdir -p $1/qml/QtQuick/NativeStyle/controls
mkdir -p $1/qml/QtQuick/LocalStorage
mkdir -p $1/qml/QtQuick/Layouts
mkdir -p $1/qml/QtQuick/Effects
mkdir -p $1/qml/QtQuick/Dialogs
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion
mkdir -p $1/qml/QtQuick/Controls
mkdir -p $1/qml/QtQuick/Controls/Universal
mkdir -p $1/qml/QtQuick/Controls/Universal/impl
mkdir -p $1/qml/QtQuick/Controls/Material
mkdir -p $1/qml/QtQuick/Controls/Material/impl
mkdir -p $1/qml/QtQuick/Controls/impl
mkdir -p $1/qml/QtQuick/Controls/Imagine
mkdir -p $1/qml/QtQuick/Controls/Imagine/impl
mkdir -p $1/qml/QtQuick/Controls/Fusion
mkdir -p $1/qml/QtQuick/Controls/Fusion/impl
mkdir -p $1/qml/QtQuick/Controls/Basic
mkdir -p $1/qml/QtQuick/Controls/Basic/impl
mkdir -p $1/qml/QtQml
mkdir -p $1/qml/QtQml/XmlListModel
mkdir -p $1/qml/QtQml/WorkerScript
mkdir -p $1/qml/QtQml/Models
mkdir -p $1/qml/QtNetwork
mkdir -p $1/qml/QtCore
mkdir -p $1/qml/Qt
mkdir -p $1/qml/Qt/test
mkdir -p $1/qml/Qt/test/controls
mkdir -p $1/qml/Qt/labs
mkdir -p $1/qml/Qt/labs/wavefrontmesh
mkdir -p $1/qml/Qt/labs/sharedimage
mkdir -p $1/qml/Qt/labs/settings
mkdir -p $1/qml/Qt/labs/qmlmodels
mkdir -p $1/qml/Qt/labs/platform
mkdir -p $1/qml/Qt/labs/folderlistmodel
mkdir -p $1/qml/Qt/labs/animation
mkdir -p $1/qml/QmlTime
mkdir -p $1/qml/QML
mkdir -p $1/qml/Assets
mkdir -p $1/qml/Assets/Downloader

# Core
cp $2/lib/libQt6Core.so.6 $1/libQt6Core.so.6
cp $2/lib/libQt6DBus.so.6 $1/libQt6DBus.so.6
cp $2/lib/libQt6Network.so.6 $1/libQt6Network.so.6
cp $2/lib/libicudata.so.73 $1/libicudata.so.73
cp $2/lib/libicui18n.so.73 $1/libicui18n.so.73
cp $2/lib/libicuio.so.73 $1/libicuio.so.73
cp $2/lib/libicutest.so.73 $1/libicutest.so.73
cp $2/lib/libicutu.so.73 $1/libicutu.so.73
cp $2/lib/libicuuc.so.73 $1/libicuuc.so.73

# Gui
cp $2/lib/libQt6Gui.so.6 $1/libQt6Gui.so.6
cp $2/lib/libQt6OpenGL.so.6 $1/libQt6OpenGL.so.6
cp $2/lib/libQt6Svg.so.6 $1/libQt6Svg.so.6
cp $2/lib/libQt6Widgets.so.6 $1/libQt6Widgets.so.6
cp $2/lib/libQt6XcbQpa.so.6 $1/libQt6XcbQpa.so.6
cp $2/plugins/iconengines/libqsvgicon.so $1/plugins/iconengines/libqsvgicon.so
cp $2/plugins/imageformats/libqgif.so $1/plugins/imageformats/libqgif.so
cp $2/plugins/imageformats/libqico.so $1/plugins/imageformats/libqico.so
cp $2/plugins/imageformats/libqjpeg.so $1/plugins/imageformats/libqjpeg.so
cp $2/plugins/imageformats/libqsvg.so $1/plugins/imageformats/libqsvg.so
cp $2/plugins/platforms/libqlinuxfb.so $1/plugins/platforms/libqlinuxfb.so
cp $2/plugins/platforms/libqoffscreen.so $1/plugins/platforms/libqoffscreen.so
cp $2/plugins/platforms/libqwayland-generic.so $1/plugins/platforms/libqwayland-generic.so
cp $2/plugins/platforms/libqwayland-xcomposite-glx.so $1/plugins/platforms/libqwayland-xcomposite-glx.so
cp $2/plugins/platforms/libqxcb.so $1/plugins/platforms/libqxcb.so
cp $2/plugins/xcbglintegrations/libqwayland-egl.so $1/plugins/xcbglintegrations/libqwayland-egl.so
cp $2/plugins/xcbglintegrations/libqwayland-generic.so $1/plugins/xcbglintegrations/libqwayland-generic.so

# QML
cp $2/lib/libQt6Qml.so.6 $1/libQt6Qml.so.6
cp $2/lib/libQt6Quick.so.6 $1/libQt6Quick.so.6
cp $2/lib/libQt6QuickControls2.so.6 $1/libQt6QuickControls2.so.6
cp $2/lib/libQt6QuickTemplates2.so.6 $1/libQt6QuickTemplates2.so.6
cp $2/lib/libQt6QuickWidgets.so.6 $1/libQt6QuickWidgets.so.6

cp $2/plugins/qmltooling/libqmldbg_debugger.so $1/plugins/qmltooling/libqmldbg_debugger.so
cp $2/plugins/qmltooling/libqmldbg_inspector.so $1/plugins/qmltooling/libqmldbg_inspector.so
cp $2/plugins/qmltooling/libqmldbg_local.so $1/plugins/qmltooling/libqmldbg_local.so
cp $2/plugins/qmltooling/libqmldbg_messages.so $1/plugins/qmltooling/libqmldbg_messages.so
cp $2/plugins/qmltooling/libqmldbg_native.so $1/plugins/qmltooling/libqmldbg_native.so
cp $2/plugins/qmltooling/libqmldbg_nativedebugger.so $1/plugins/qmltooling/libqmldbg_nativedebugger.so
cp $2/plugins/qmltooling/libqmldbg_preview.so $1/plugins/qmltooling/libqmldbg_preview.so
cp $2/plugins/qmltooling/libqmldbg_profiler.so $1/plugins/qmltooling/libqmldbg_profiler.so
cp $2/plugins/qmltooling/libqmldbg_quickprofiler.so $1/plugins/qmltooling/libqmldbg_quickprofiler.so
cp $2/plugins/qmltooling/libqmldbg_server.so $1/plugins/qmltooling/libqmldbg_server.so
cp $2/plugins/qmltooling/libqmldbg_tcp.so $1/plugins/qmltooling/libqmldbg_tcp.so

cp $2/qml/builtins.qmltypes $1/qml/builtins.qmltypes
cp $2/qml/jsroot.qmltypes $1/qml/jsroot.qmltypes
cp $2/qml/QtTest/plugins.qmltypes $1/qml/QtTest/plugins.qmltypes
cp $2/qml/QtTest/qmldir $1/qml/QtTest/qmldir
cp $2/qml/QtTest/libquicktestplugin.so $1/qml/QtTest/libquicktestplugin.so
cp $2/qml/QtTest/SignalSpy.qml $1/qml/QtTest/SignalSpy.qml
cp $2/qml/QtTest/TestCase.qml $1/qml/QtTest/TestCase.qml
cp $2/qml/QtTest/testlogger.js $1/qml/QtTest/testlogger.js
cp $2/qml/QtTest/TestSchedule.qml $1/qml/QtTest/TestSchedule.qml
cp $2/qml/QtQuick/plugins.qmltypes $1/qml/QtQuick/plugins.qmltypes
cp $2/qml/QtQuick/qmldir $1/qml/QtQuick/qmldir
cp $2/qml/QtQuick/libqtquick2plugin.so $1/qml/QtQuick/libqtquick2plugin.so
cp $2/qml/QtQuick/Window/qmldir $1/qml/QtQuick/Window/qmldir
cp $2/qml/QtQuick/Window/quickwindow.qmltypes $1/qml/QtQuick/Window/quickwindow.qmltypes
cp $2/qml/QtQuick/Window/libquickwindowplugin.so $1/qml/QtQuick/Window/libquickwindowplugin.so
cp $2/qml/QtQuick/VectorImage/plugins.qmltypes $1/qml/QtQuick/VectorImage/plugins.qmltypes
cp $2/qml/QtQuick/VectorImage/qmldir $1/qml/QtQuick/VectorImage/qmldir
cp $2/qml/QtQuick/VectorImage/libqquickvectorimageplugin.so $1/qml/QtQuick/VectorImage/libqquickvectorimageplugin.so
cp $2/qml/QtQuick/tooling/Component.qml $1/qml/QtQuick/tooling/Component.qml
cp $2/qml/QtQuick/tooling/Enum.qml $1/qml/QtQuick/tooling/Enum.qml
cp $2/qml/QtQuick/tooling/Member.qml $1/qml/QtQuick/tooling/Member.qml
cp $2/qml/QtQuick/tooling/Method.qml $1/qml/QtQuick/tooling/Method.qml
cp $2/qml/QtQuick/tooling/Module.qml $1/qml/QtQuick/tooling/Module.qml
cp $2/qml/QtQuick/tooling/Parameter.qml $1/qml/QtQuick/tooling/Parameter.qml
cp $2/qml/QtQuick/tooling/Property.qml $1/qml/QtQuick/tooling/Property.qml
cp $2/qml/QtQuick/tooling/qmldir $1/qml/QtQuick/tooling/qmldir
cp $2/qml/QtQuick/tooling/quicktooling.qmltypes $1/qml/QtQuick/tooling/quicktooling.qmltypes
cp $2/qml/QtQuick/tooling/libquicktoolingplugin.so $1/qml/QtQuick/tooling/libquicktoolingplugin.so
cp $2/qml/QtQuick/tooling/Signal.qml $1/qml/QtQuick/tooling/Signal.qml
cp $2/qml/QtQuick/Templates/plugins.qmltypes $1/qml/QtQuick/Templates/plugins.qmltypes
cp $2/qml/QtQuick/Templates/qmldir $1/qml/QtQuick/Templates/qmldir
cp $2/qml/QtQuick/Templates/libqtquicktemplates2plugin.so $1/qml/QtQuick/Templates/libqtquicktemplates2plugin.so
cp $2/qml/QtQuick/Shapes/plugins.qmltypes $1/qml/QtQuick/Shapes/plugins.qmltypes
cp $2/qml/QtQuick/Shapes/qmldir $1/qml/QtQuick/Shapes/qmldir
cp $2/qml/QtQuick/Shapes/libqmlshapesplugin.so $1/qml/QtQuick/Shapes/libqmlshapesplugin.so
cp $2/qml/QtQuick/Particles/libparticlesplugin.so $1/qml/QtQuick/Particles/libparticlesplugin.so
cp $2/qml/QtQuick/Particles/plugins.qmltypes $1/qml/QtQuick/Particles/plugins.qmltypes
cp $2/qml/QtQuick/Particles/qmldir $1/qml/QtQuick/Particles/qmldir
cp $2/qml/QtQuick/NativeStyle/plugins.qmltypes $1/qml/QtQuick/NativeStyle/plugins.qmltypes
cp $2/qml/QtQuick/NativeStyle/qmldir $1/qml/QtQuick/NativeStyle/qmldir
cp $2/qml/QtQuick/NativeStyle/libqtquickcontrols2nativestyleplugin.so $1/qml/QtQuick/NativeStyle/libqtquickcontrols2nativestyleplugin.so
cp $2/qml/QtQuick/NativeStyle/controls/DefaultButton.qml $1/qml/QtQuick/NativeStyle/controls/DefaultButton.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultCheckBox.qml $1/qml/QtQuick/NativeStyle/controls/DefaultCheckBox.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultComboBox.qml $1/qml/QtQuick/NativeStyle/controls/DefaultComboBox.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultDial.qml $1/qml/QtQuick/NativeStyle/controls/DefaultDial.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultFrame.qml $1/qml/QtQuick/NativeStyle/controls/DefaultFrame.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultGroupBox.qml $1/qml/QtQuick/NativeStyle/controls/DefaultGroupBox.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultItemDelegate.qml $1/qml/QtQuick/NativeStyle/controls/DefaultItemDelegate.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultItemDelegateIconLabel.qml $1/qml/QtQuick/NativeStyle/controls/DefaultItemDelegateIconLabel.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultProgressBar.qml $1/qml/QtQuick/NativeStyle/controls/DefaultProgressBar.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultRadioButton.qml $1/qml/QtQuick/NativeStyle/controls/DefaultRadioButton.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultRadioDelegate.qml $1/qml/QtQuick/NativeStyle/controls/DefaultRadioDelegate.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultScrollBar.qml $1/qml/QtQuick/NativeStyle/controls/DefaultScrollBar.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultSlider.qml $1/qml/QtQuick/NativeStyle/controls/DefaultSlider.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultSpinBox.qml $1/qml/QtQuick/NativeStyle/controls/DefaultSpinBox.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultTextArea.qml $1/qml/QtQuick/NativeStyle/controls/DefaultTextArea.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultTextField.qml $1/qml/QtQuick/NativeStyle/controls/DefaultTextField.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultTreeViewDelegate.qml $1/qml/QtQuick/NativeStyle/controls/DefaultTreeViewDelegate.qml
cp $2/qml/QtQuick/NativeStyle/controls/qmldir $1/qml/QtQuick/NativeStyle/controls/qmldir
cp $2/qml/QtQuick/LocalStorage/plugins.qmltypes $1/qml/QtQuick/LocalStorage/plugins.qmltypes
cp $2/qml/QtQuick/LocalStorage/qmldir $1/qml/QtQuick/LocalStorage/qmldir
cp $2/qml/QtQuick/LocalStorage/libqmllocalstorageplugin.so $1/qml/QtQuick/LocalStorage/libqmllocalstorageplugin.so
cp $2/qml/QtQuick/Layouts/plugins.qmltypes $1/qml/QtQuick/Layouts/plugins.qmltypes
cp $2/qml/QtQuick/Layouts/qmldir $1/qml/QtQuick/Layouts/qmldir
cp $2/qml/QtQuick/Layouts/libqquicklayoutsplugin.so $1/qml/QtQuick/Layouts/libqquicklayoutsplugin.so
cp $2/qml/QtQuick/Effects/libeffectsplugin.so $1/qml/QtQuick/Effects/libeffectsplugin.so
cp $2/qml/QtQuick/Effects/plugins.qmltypes $1/qml/QtQuick/Effects/plugins.qmltypes
cp $2/qml/QtQuick/Effects/qmldir $1/qml/QtQuick/Effects/qmldir
cp $2/qml/QtQuick/Dialogs/plugins.qmltypes $1/qml/QtQuick/Dialogs/plugins.qmltypes
cp $2/qml/QtQuick/Dialogs/qmldir $1/qml/QtQuick/Dialogs/qmldir
cp $2/qml/QtQuick/Dialogs/libqtquickdialogsplugin.so $1/qml/QtQuick/Dialogs/libqtquickdialogsplugin.so
cp $2/qml/QtQuick/Dialogs/quickimpl/plugins.qmltypes $1/qml/QtQuick/Dialogs/quickimpl/plugins.qmltypes
cp $2/qml/QtQuick/Dialogs/quickimpl/qmldir $1/qml/QtQuick/Dialogs/quickimpl/qmldir
cp $2/qml/QtQuick/Dialogs/quickimpl/libqtquickdialogs2quickimplplugin.so $1/qml/QtQuick/Dialogs/quickimpl/libqtquickdialogs2quickimplplugin.so
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/ColorDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/ColorDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/ColorInputs.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/ColorInputs.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FileDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/FileDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FileDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/FileDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FileDialogDelegateLabel.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/FileDialogDelegateLabel.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FolderBreadcrumbBar.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/FolderBreadcrumbBar.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialogDelegateLabel.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialogDelegateLabel.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FontDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/FontDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FontDialogContent.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/FontDialogContent.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/HueGradient.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/HueGradient.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/MessageDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/MessageDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/PickerHandle.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/PickerHandle.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/SaturationLightnessPicker.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/SaturationLightnessPicker.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/ColorDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/ColorDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FileDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FileDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FileDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FileDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FolderBreadcrumbBar.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FolderBreadcrumbBar.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FolderDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FolderDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FolderDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FolderDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FontDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/FontDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/MessageDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal/MessageDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Material/ColorDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material/ColorDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FileDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FileDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FileDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FileDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FolderBreadcrumbBar.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FolderBreadcrumbBar.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FolderDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FolderDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FolderDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FolderDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FontDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material/FontDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Material/MessageDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material/MessageDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/ColorDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/ColorDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FileDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FileDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FileDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FileDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FolderBreadcrumbBar.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FolderBreadcrumbBar.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FolderDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FolderDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FolderDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FolderDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FontDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/FontDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/MessageDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine/MessageDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/ColorDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/ColorDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FileDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FileDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FileDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FileDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FolderBreadcrumbBar.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FolderBreadcrumbBar.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FolderDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FolderDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FolderDialogDelegate.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FolderDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FontDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/FontDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/MessageDialog.qml $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion/MessageDialog.qml
cp $2/qml/QtQuick/Controls/plugins.qmltypes $1/qml/QtQuick/Controls/plugins.qmltypes
cp $2/qml/QtQuick/Controls/qmldir $1/qml/QtQuick/Controls/qmldir
cp $2/qml/QtQuick/Controls/libqtquickcontrols2plugin.so $1/qml/QtQuick/Controls/libqtquickcontrols2plugin.so
cp $2/qml/QtQuick/Controls/Universal/ApplicationWindow.qml $1/qml/QtQuick/Controls/Universal/ApplicationWindow.qml
cp $2/qml/QtQuick/Controls/Universal/BusyIndicator.qml $1/qml/QtQuick/Controls/Universal/BusyIndicator.qml
cp $2/qml/QtQuick/Controls/Universal/Button.qml $1/qml/QtQuick/Controls/Universal/Button.qml
cp $2/qml/QtQuick/Controls/Universal/CheckBox.qml $1/qml/QtQuick/Controls/Universal/CheckBox.qml
cp $2/qml/QtQuick/Controls/Universal/CheckDelegate.qml $1/qml/QtQuick/Controls/Universal/CheckDelegate.qml
cp $2/qml/QtQuick/Controls/Universal/ComboBox.qml $1/qml/QtQuick/Controls/Universal/ComboBox.qml
cp $2/qml/QtQuick/Controls/Universal/DelayButton.qml $1/qml/QtQuick/Controls/Universal/DelayButton.qml
cp $2/qml/QtQuick/Controls/Universal/Dial.qml $1/qml/QtQuick/Controls/Universal/Dial.qml
cp $2/qml/QtQuick/Controls/Universal/Dialog.qml $1/qml/QtQuick/Controls/Universal/Dialog.qml
cp $2/qml/QtQuick/Controls/Universal/DialogButtonBox.qml $1/qml/QtQuick/Controls/Universal/DialogButtonBox.qml
cp $2/qml/QtQuick/Controls/Universal/Drawer.qml $1/qml/QtQuick/Controls/Universal/Drawer.qml
cp $2/qml/QtQuick/Controls/Universal/Frame.qml $1/qml/QtQuick/Controls/Universal/Frame.qml
cp $2/qml/QtQuick/Controls/Universal/GroupBox.qml $1/qml/QtQuick/Controls/Universal/GroupBox.qml
cp $2/qml/QtQuick/Controls/Universal/HorizontalHeaderView.qml $1/qml/QtQuick/Controls/Universal/HorizontalHeaderView.qml
cp $2/qml/QtQuick/Controls/Universal/ItemDelegate.qml $1/qml/QtQuick/Controls/Universal/ItemDelegate.qml
cp $2/qml/QtQuick/Controls/Universal/Label.qml $1/qml/QtQuick/Controls/Universal/Label.qml
cp $2/qml/QtQuick/Controls/Universal/Menu.qml $1/qml/QtQuick/Controls/Universal/Menu.qml
cp $2/qml/QtQuick/Controls/Universal/MenuBar.qml $1/qml/QtQuick/Controls/Universal/MenuBar.qml
cp $2/qml/QtQuick/Controls/Universal/MenuBarItem.qml $1/qml/QtQuick/Controls/Universal/MenuBarItem.qml
cp $2/qml/QtQuick/Controls/Universal/MenuItem.qml $1/qml/QtQuick/Controls/Universal/MenuItem.qml
cp $2/qml/QtQuick/Controls/Universal/MenuSeparator.qml $1/qml/QtQuick/Controls/Universal/MenuSeparator.qml
cp $2/qml/QtQuick/Controls/Universal/Page.qml $1/qml/QtQuick/Controls/Universal/Page.qml
cp $2/qml/QtQuick/Controls/Universal/PageIndicator.qml $1/qml/QtQuick/Controls/Universal/PageIndicator.qml
cp $2/qml/QtQuick/Controls/Universal/Pane.qml $1/qml/QtQuick/Controls/Universal/Pane.qml
cp $2/qml/QtQuick/Controls/Universal/plugins.qmltypes $1/qml/QtQuick/Controls/Universal/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Universal/Popup.qml $1/qml/QtQuick/Controls/Universal/Popup.qml
cp $2/qml/QtQuick/Controls/Universal/ProgressBar.qml $1/qml/QtQuick/Controls/Universal/ProgressBar.qml
cp $2/qml/QtQuick/Controls/Universal/qmldir $1/qml/QtQuick/Controls/Universal/qmldir
cp $2/qml/QtQuick/Controls/Universal/libqtquickcontrols2universalstyleplugin.so $1/qml/QtQuick/Controls/Universal/libqtquickcontrols2universalstyleplugin.so
cp $2/qml/QtQuick/Controls/Universal/RadioButton.qml $1/qml/QtQuick/Controls/Universal/RadioButton.qml
cp $2/qml/QtQuick/Controls/Universal/RadioDelegate.qml $1/qml/QtQuick/Controls/Universal/RadioDelegate.qml
cp $2/qml/QtQuick/Controls/Universal/RangeSlider.qml $1/qml/QtQuick/Controls/Universal/RangeSlider.qml
cp $2/qml/QtQuick/Controls/Universal/RoundButton.qml $1/qml/QtQuick/Controls/Universal/RoundButton.qml
cp $2/qml/QtQuick/Controls/Universal/ScrollBar.qml $1/qml/QtQuick/Controls/Universal/ScrollBar.qml
cp $2/qml/QtQuick/Controls/Universal/ScrollIndicator.qml $1/qml/QtQuick/Controls/Universal/ScrollIndicator.qml
cp $2/qml/QtQuick/Controls/Universal/ScrollView.qml $1/qml/QtQuick/Controls/Universal/ScrollView.qml
cp $2/qml/QtQuick/Controls/Universal/SelectionRectangle.qml $1/qml/QtQuick/Controls/Universal/SelectionRectangle.qml
cp $2/qml/QtQuick/Controls/Universal/Slider.qml $1/qml/QtQuick/Controls/Universal/Slider.qml
cp $2/qml/QtQuick/Controls/Universal/SpinBox.qml $1/qml/QtQuick/Controls/Universal/SpinBox.qml
cp $2/qml/QtQuick/Controls/Universal/SplitView.qml $1/qml/QtQuick/Controls/Universal/SplitView.qml
cp $2/qml/QtQuick/Controls/Universal/StackView.qml $1/qml/QtQuick/Controls/Universal/StackView.qml
cp $2/qml/QtQuick/Controls/Universal/SwipeDelegate.qml $1/qml/QtQuick/Controls/Universal/SwipeDelegate.qml
cp $2/qml/QtQuick/Controls/Universal/Switch.qml $1/qml/QtQuick/Controls/Universal/Switch.qml
cp $2/qml/QtQuick/Controls/Universal/SwitchDelegate.qml $1/qml/QtQuick/Controls/Universal/SwitchDelegate.qml
cp $2/qml/QtQuick/Controls/Universal/TabBar.qml $1/qml/QtQuick/Controls/Universal/TabBar.qml
cp $2/qml/QtQuick/Controls/Universal/TabButton.qml $1/qml/QtQuick/Controls/Universal/TabButton.qml
cp $2/qml/QtQuick/Controls/Universal/TextArea.qml $1/qml/QtQuick/Controls/Universal/TextArea.qml
cp $2/qml/QtQuick/Controls/Universal/TextField.qml $1/qml/QtQuick/Controls/Universal/TextField.qml
cp $2/qml/QtQuick/Controls/Universal/ToolBar.qml $1/qml/QtQuick/Controls/Universal/ToolBar.qml
cp $2/qml/QtQuick/Controls/Universal/ToolButton.qml $1/qml/QtQuick/Controls/Universal/ToolButton.qml
cp $2/qml/QtQuick/Controls/Universal/ToolSeparator.qml $1/qml/QtQuick/Controls/Universal/ToolSeparator.qml
cp $2/qml/QtQuick/Controls/Universal/ToolTip.qml $1/qml/QtQuick/Controls/Universal/ToolTip.qml
cp $2/qml/QtQuick/Controls/Universal/Tumbler.qml $1/qml/QtQuick/Controls/Universal/Tumbler.qml
cp $2/qml/QtQuick/Controls/Universal/VerticalHeaderView.qml $1/qml/QtQuick/Controls/Universal/VerticalHeaderView.qml
cp $2/qml/QtQuick/Controls/Universal/impl/CheckIndicator.qml $1/qml/QtQuick/Controls/Universal/impl/CheckIndicator.qml
cp $2/qml/QtQuick/Controls/Universal/impl/plugins.qmltypes $1/qml/QtQuick/Controls/Universal/impl/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Universal/impl/qmldir $1/qml/QtQuick/Controls/Universal/impl/qmldir
cp $2/qml/QtQuick/Controls/Universal/impl/libqtquickcontrols2universalstyleimplplugin.so $1/qml/QtQuick/Controls/Universal/impl/libqtquickcontrols2universalstyleimplplugin.so
cp $2/qml/QtQuick/Controls/Universal/impl/RadioIndicator.qml $1/qml/QtQuick/Controls/Universal/impl/RadioIndicator.qml
cp $2/qml/QtQuick/Controls/Universal/impl/SwitchIndicator.qml $1/qml/QtQuick/Controls/Universal/impl/SwitchIndicator.qml
cp $2/qml/QtQuick/Controls/Material/ApplicationWindow.qml $1/qml/QtQuick/Controls/Material/ApplicationWindow.qml
cp $2/qml/QtQuick/Controls/Material/BusyIndicator.qml $1/qml/QtQuick/Controls/Material/BusyIndicator.qml
cp $2/qml/QtQuick/Controls/Material/Button.qml $1/qml/QtQuick/Controls/Material/Button.qml
cp $2/qml/QtQuick/Controls/Material/CheckBox.qml $1/qml/QtQuick/Controls/Material/CheckBox.qml
cp $2/qml/QtQuick/Controls/Material/CheckDelegate.qml $1/qml/QtQuick/Controls/Material/CheckDelegate.qml
cp $2/qml/QtQuick/Controls/Material/ComboBox.qml $1/qml/QtQuick/Controls/Material/ComboBox.qml
cp $2/qml/QtQuick/Controls/Material/DelayButton.qml $1/qml/QtQuick/Controls/Material/DelayButton.qml
cp $2/qml/QtQuick/Controls/Material/Dial.qml $1/qml/QtQuick/Controls/Material/Dial.qml
cp $2/qml/QtQuick/Controls/Material/Dialog.qml $1/qml/QtQuick/Controls/Material/Dialog.qml
cp $2/qml/QtQuick/Controls/Material/DialogButtonBox.qml $1/qml/QtQuick/Controls/Material/DialogButtonBox.qml
cp $2/qml/QtQuick/Controls/Material/Drawer.qml $1/qml/QtQuick/Controls/Material/Drawer.qml
cp $2/qml/QtQuick/Controls/Material/Frame.qml $1/qml/QtQuick/Controls/Material/Frame.qml
cp $2/qml/QtQuick/Controls/Material/GroupBox.qml $1/qml/QtQuick/Controls/Material/GroupBox.qml
cp $2/qml/QtQuick/Controls/Material/HorizontalHeaderView.qml $1/qml/QtQuick/Controls/Material/HorizontalHeaderView.qml
cp $2/qml/QtQuick/Controls/Material/ItemDelegate.qml $1/qml/QtQuick/Controls/Material/ItemDelegate.qml
cp $2/qml/QtQuick/Controls/Material/Label.qml $1/qml/QtQuick/Controls/Material/Label.qml
cp $2/qml/QtQuick/Controls/Material/Menu.qml $1/qml/QtQuick/Controls/Material/Menu.qml
cp $2/qml/QtQuick/Controls/Material/MenuBar.qml $1/qml/QtQuick/Controls/Material/MenuBar.qml
cp $2/qml/QtQuick/Controls/Material/MenuBarItem.qml $1/qml/QtQuick/Controls/Material/MenuBarItem.qml
cp $2/qml/QtQuick/Controls/Material/MenuItem.qml $1/qml/QtQuick/Controls/Material/MenuItem.qml
cp $2/qml/QtQuick/Controls/Material/MenuSeparator.qml $1/qml/QtQuick/Controls/Material/MenuSeparator.qml
cp $2/qml/QtQuick/Controls/Material/Page.qml $1/qml/QtQuick/Controls/Material/Page.qml
cp $2/qml/QtQuick/Controls/Material/PageIndicator.qml $1/qml/QtQuick/Controls/Material/PageIndicator.qml
cp $2/qml/QtQuick/Controls/Material/Pane.qml $1/qml/QtQuick/Controls/Material/Pane.qml
cp $2/qml/QtQuick/Controls/Material/plugins.qmltypes $1/qml/QtQuick/Controls/Material/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Material/Popup.qml $1/qml/QtQuick/Controls/Material/Popup.qml
cp $2/qml/QtQuick/Controls/Material/ProgressBar.qml $1/qml/QtQuick/Controls/Material/ProgressBar.qml
cp $2/qml/QtQuick/Controls/Material/qmldir $1/qml/QtQuick/Controls/Material/qmldir
cp $2/qml/QtQuick/Controls/Material/libqtquickcontrols2materialstyleplugin.so $1/qml/QtQuick/Controls/Material/libqtquickcontrols2materialstyleplugin.so
cp $2/qml/QtQuick/Controls/Material/RadioButton.qml $1/qml/QtQuick/Controls/Material/RadioButton.qml
cp $2/qml/QtQuick/Controls/Material/RadioDelegate.qml $1/qml/QtQuick/Controls/Material/RadioDelegate.qml
cp $2/qml/QtQuick/Controls/Material/RangeSlider.qml $1/qml/QtQuick/Controls/Material/RangeSlider.qml
cp $2/qml/QtQuick/Controls/Material/RoundButton.qml $1/qml/QtQuick/Controls/Material/RoundButton.qml
cp $2/qml/QtQuick/Controls/Material/ScrollBar.qml $1/qml/QtQuick/Controls/Material/ScrollBar.qml
cp $2/qml/QtQuick/Controls/Material/ScrollIndicator.qml $1/qml/QtQuick/Controls/Material/ScrollIndicator.qml
cp $2/qml/QtQuick/Controls/Material/ScrollView.qml $1/qml/QtQuick/Controls/Material/ScrollView.qml
cp $2/qml/QtQuick/Controls/Material/SelectionRectangle.qml $1/qml/QtQuick/Controls/Material/SelectionRectangle.qml
cp $2/qml/QtQuick/Controls/Material/Slider.qml $1/qml/QtQuick/Controls/Material/Slider.qml
cp $2/qml/QtQuick/Controls/Material/SpinBox.qml $1/qml/QtQuick/Controls/Material/SpinBox.qml
cp $2/qml/QtQuick/Controls/Material/SplitView.qml $1/qml/QtQuick/Controls/Material/SplitView.qml
cp $2/qml/QtQuick/Controls/Material/StackView.qml $1/qml/QtQuick/Controls/Material/StackView.qml
cp $2/qml/QtQuick/Controls/Material/SwipeDelegate.qml $1/qml/QtQuick/Controls/Material/SwipeDelegate.qml
cp $2/qml/QtQuick/Controls/Material/SwipeView.qml $1/qml/QtQuick/Controls/Material/SwipeView.qml
cp $2/qml/QtQuick/Controls/Material/Switch.qml $1/qml/QtQuick/Controls/Material/Switch.qml
cp $2/qml/QtQuick/Controls/Material/SwitchDelegate.qml $1/qml/QtQuick/Controls/Material/SwitchDelegate.qml
cp $2/qml/QtQuick/Controls/Material/TabBar.qml $1/qml/QtQuick/Controls/Material/TabBar.qml
cp $2/qml/QtQuick/Controls/Material/TabButton.qml $1/qml/QtQuick/Controls/Material/TabButton.qml
cp $2/qml/QtQuick/Controls/Material/TextArea.qml $1/qml/QtQuick/Controls/Material/TextArea.qml
cp $2/qml/QtQuick/Controls/Material/TextField.qml $1/qml/QtQuick/Controls/Material/TextField.qml
cp $2/qml/QtQuick/Controls/Material/ToolBar.qml $1/qml/QtQuick/Controls/Material/ToolBar.qml
cp $2/qml/QtQuick/Controls/Material/ToolButton.qml $1/qml/QtQuick/Controls/Material/ToolButton.qml
cp $2/qml/QtQuick/Controls/Material/ToolSeparator.qml $1/qml/QtQuick/Controls/Material/ToolSeparator.qml
cp $2/qml/QtQuick/Controls/Material/ToolTip.qml $1/qml/QtQuick/Controls/Material/ToolTip.qml
cp $2/qml/QtQuick/Controls/Material/TreeViewDelegate.qml $1/qml/QtQuick/Controls/Material/TreeViewDelegate.qml
cp $2/qml/QtQuick/Controls/Material/Tumbler.qml $1/qml/QtQuick/Controls/Material/Tumbler.qml
cp $2/qml/QtQuick/Controls/Material/VerticalHeaderView.qml $1/qml/QtQuick/Controls/Material/VerticalHeaderView.qml
cp $2/qml/QtQuick/Controls/Material/impl/BoxShadow.qml $1/qml/QtQuick/Controls/Material/impl/BoxShadow.qml
cp $2/qml/QtQuick/Controls/Material/impl/CheckIndicator.qml $1/qml/QtQuick/Controls/Material/impl/CheckIndicator.qml
cp $2/qml/QtQuick/Controls/Material/impl/CursorDelegate.qml $1/qml/QtQuick/Controls/Material/impl/CursorDelegate.qml
cp $2/qml/QtQuick/Controls/Material/impl/ElevationEffect.qml $1/qml/QtQuick/Controls/Material/impl/ElevationEffect.qml
cp $2/qml/QtQuick/Controls/Material/impl/plugins.qmltypes $1/qml/QtQuick/Controls/Material/impl/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Material/impl/qmldir $1/qml/QtQuick/Controls/Material/impl/qmldir
cp $2/qml/QtQuick/Controls/Material/impl/libqtquickcontrols2materialstyleimplplugin.so $1/qml/QtQuick/Controls/Material/impl/libqtquickcontrols2materialstyleimplplugin.so
cp $2/qml/QtQuick/Controls/Material/impl/RadioIndicator.qml $1/qml/QtQuick/Controls/Material/impl/RadioIndicator.qml
cp $2/qml/QtQuick/Controls/Material/impl/RectangularGlow.qml $1/qml/QtQuick/Controls/Material/impl/RectangularGlow.qml
cp $2/qml/QtQuick/Controls/Material/impl/RoundedElevationEffect.qml $1/qml/QtQuick/Controls/Material/impl/RoundedElevationEffect.qml
cp $2/qml/QtQuick/Controls/Material/impl/SliderHandle.qml $1/qml/QtQuick/Controls/Material/impl/SliderHandle.qml
cp $2/qml/QtQuick/Controls/Material/impl/SwitchIndicator.qml $1/qml/QtQuick/Controls/Material/impl/SwitchIndicator.qml
cp $2/qml/QtQuick/Controls/impl/plugins.qmltypes $1/qml/QtQuick/Controls/impl/plugins.qmltypes
cp $2/qml/QtQuick/Controls/impl/qmldir $1/qml/QtQuick/Controls/impl/qmldir
cp $2/qml/QtQuick/Controls/impl/libqtquickcontrols2implplugin.so $1/qml/QtQuick/Controls/impl/libqtquickcontrols2implplugin.so
cp $2/qml/QtQuick/Controls/Imagine/ApplicationWindow.qml $1/qml/QtQuick/Controls/Imagine/ApplicationWindow.qml
cp $2/qml/QtQuick/Controls/Imagine/BusyIndicator.qml $1/qml/QtQuick/Controls/Imagine/BusyIndicator.qml
cp $2/qml/QtQuick/Controls/Imagine/Button.qml $1/qml/QtQuick/Controls/Imagine/Button.qml
cp $2/qml/QtQuick/Controls/Imagine/CheckBox.qml $1/qml/QtQuick/Controls/Imagine/CheckBox.qml
cp $2/qml/QtQuick/Controls/Imagine/CheckDelegate.qml $1/qml/QtQuick/Controls/Imagine/CheckDelegate.qml
cp $2/qml/QtQuick/Controls/Imagine/ComboBox.qml $1/qml/QtQuick/Controls/Imagine/ComboBox.qml
cp $2/qml/QtQuick/Controls/Imagine/DelayButton.qml $1/qml/QtQuick/Controls/Imagine/DelayButton.qml
cp $2/qml/QtQuick/Controls/Imagine/Dial.qml $1/qml/QtQuick/Controls/Imagine/Dial.qml
cp $2/qml/QtQuick/Controls/Imagine/Dialog.qml $1/qml/QtQuick/Controls/Imagine/Dialog.qml
cp $2/qml/QtQuick/Controls/Imagine/DialogButtonBox.qml $1/qml/QtQuick/Controls/Imagine/DialogButtonBox.qml
cp $2/qml/QtQuick/Controls/Imagine/Drawer.qml $1/qml/QtQuick/Controls/Imagine/Drawer.qml
cp $2/qml/QtQuick/Controls/Imagine/Frame.qml $1/qml/QtQuick/Controls/Imagine/Frame.qml
cp $2/qml/QtQuick/Controls/Imagine/GroupBox.qml $1/qml/QtQuick/Controls/Imagine/GroupBox.qml
cp $2/qml/QtQuick/Controls/Imagine/HorizontalHeaderView.qml $1/qml/QtQuick/Controls/Imagine/HorizontalHeaderView.qml
cp $2/qml/QtQuick/Controls/Imagine/ItemDelegate.qml $1/qml/QtQuick/Controls/Imagine/ItemDelegate.qml
cp $2/qml/QtQuick/Controls/Imagine/Label.qml $1/qml/QtQuick/Controls/Imagine/Label.qml
cp $2/qml/QtQuick/Controls/Imagine/Menu.qml $1/qml/QtQuick/Controls/Imagine/Menu.qml
cp $2/qml/QtQuick/Controls/Imagine/MenuItem.qml $1/qml/QtQuick/Controls/Imagine/MenuItem.qml
cp $2/qml/QtQuick/Controls/Imagine/MenuSeparator.qml $1/qml/QtQuick/Controls/Imagine/MenuSeparator.qml
cp $2/qml/QtQuick/Controls/Imagine/Page.qml $1/qml/QtQuick/Controls/Imagine/Page.qml
cp $2/qml/QtQuick/Controls/Imagine/PageIndicator.qml $1/qml/QtQuick/Controls/Imagine/PageIndicator.qml
cp $2/qml/QtQuick/Controls/Imagine/Pane.qml $1/qml/QtQuick/Controls/Imagine/Pane.qml
cp $2/qml/QtQuick/Controls/Imagine/plugins.qmltypes $1/qml/QtQuick/Controls/Imagine/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Imagine/Popup.qml $1/qml/QtQuick/Controls/Imagine/Popup.qml
cp $2/qml/QtQuick/Controls/Imagine/ProgressBar.qml $1/qml/QtQuick/Controls/Imagine/ProgressBar.qml
cp $2/qml/QtQuick/Controls/Imagine/qmldir $1/qml/QtQuick/Controls/Imagine/qmldir
cp $2/qml/QtQuick/Controls/Imagine/libqtquickcontrols2imaginestyleplugin.so $1/qml/QtQuick/Controls/Imagine/libqtquickcontrols2imaginestyleplugin.so
cp $2/qml/QtQuick/Controls/Imagine/RadioButton.qml $1/qml/QtQuick/Controls/Imagine/RadioButton.qml
cp $2/qml/QtQuick/Controls/Imagine/RadioDelegate.qml $1/qml/QtQuick/Controls/Imagine/RadioDelegate.qml
cp $2/qml/QtQuick/Controls/Imagine/RangeSlider.qml $1/qml/QtQuick/Controls/Imagine/RangeSlider.qml
cp $2/qml/QtQuick/Controls/Imagine/RoundButton.qml $1/qml/QtQuick/Controls/Imagine/RoundButton.qml
cp $2/qml/QtQuick/Controls/Imagine/ScrollBar.qml $1/qml/QtQuick/Controls/Imagine/ScrollBar.qml
cp $2/qml/QtQuick/Controls/Imagine/ScrollIndicator.qml $1/qml/QtQuick/Controls/Imagine/ScrollIndicator.qml
cp $2/qml/QtQuick/Controls/Imagine/ScrollView.qml $1/qml/QtQuick/Controls/Imagine/ScrollView.qml
cp $2/qml/QtQuick/Controls/Imagine/SelectionRectangle.qml $1/qml/QtQuick/Controls/Imagine/SelectionRectangle.qml
cp $2/qml/QtQuick/Controls/Imagine/Slider.qml $1/qml/QtQuick/Controls/Imagine/Slider.qml
cp $2/qml/QtQuick/Controls/Imagine/SpinBox.qml $1/qml/QtQuick/Controls/Imagine/SpinBox.qml
cp $2/qml/QtQuick/Controls/Imagine/SplitView.qml $1/qml/QtQuick/Controls/Imagine/SplitView.qml
cp $2/qml/QtQuick/Controls/Imagine/StackView.qml $1/qml/QtQuick/Controls/Imagine/StackView.qml
cp $2/qml/QtQuick/Controls/Imagine/SwipeDelegate.qml $1/qml/QtQuick/Controls/Imagine/SwipeDelegate.qml
cp $2/qml/QtQuick/Controls/Imagine/SwipeView.qml $1/qml/QtQuick/Controls/Imagine/SwipeView.qml
cp $2/qml/QtQuick/Controls/Imagine/Switch.qml $1/qml/QtQuick/Controls/Imagine/Switch.qml
cp $2/qml/QtQuick/Controls/Imagine/SwitchDelegate.qml $1/qml/QtQuick/Controls/Imagine/SwitchDelegate.qml
cp $2/qml/QtQuick/Controls/Imagine/TabBar.qml $1/qml/QtQuick/Controls/Imagine/TabBar.qml
cp $2/qml/QtQuick/Controls/Imagine/TabButton.qml $1/qml/QtQuick/Controls/Imagine/TabButton.qml
cp $2/qml/QtQuick/Controls/Imagine/TextArea.qml $1/qml/QtQuick/Controls/Imagine/TextArea.qml
cp $2/qml/QtQuick/Controls/Imagine/TextField.qml $1/qml/QtQuick/Controls/Imagine/TextField.qml
cp $2/qml/QtQuick/Controls/Imagine/ToolBar.qml $1/qml/QtQuick/Controls/Imagine/ToolBar.qml
cp $2/qml/QtQuick/Controls/Imagine/ToolButton.qml $1/qml/QtQuick/Controls/Imagine/ToolButton.qml
cp $2/qml/QtQuick/Controls/Imagine/ToolSeparator.qml $1/qml/QtQuick/Controls/Imagine/ToolSeparator.qml
cp $2/qml/QtQuick/Controls/Imagine/ToolTip.qml $1/qml/QtQuick/Controls/Imagine/ToolTip.qml
cp $2/qml/QtQuick/Controls/Imagine/Tumbler.qml $1/qml/QtQuick/Controls/Imagine/Tumbler.qml
cp $2/qml/QtQuick/Controls/Imagine/VerticalHeaderView.qml $1/qml/QtQuick/Controls/Imagine/VerticalHeaderView.qml
cp $2/qml/QtQuick/Controls/Imagine/impl/OpacityMask.qml $1/qml/QtQuick/Controls/Imagine/impl/OpacityMask.qml
cp $2/qml/QtQuick/Controls/Imagine/impl/qmldir $1/qml/QtQuick/Controls/Imagine/impl/qmldir
cp $2/qml/QtQuick/Controls/Imagine/impl/libqtquickcontrols2imaginestyleimplplugin.so $1/qml/QtQuick/Controls/Imagine/impl/libqtquickcontrols2imaginestyleimplplugin.so
cp $2/qml/QtQuick/Controls/Imagine/impl/QuickControls2ImagineStyleImpl.qmltypes $1/qml/QtQuick/Controls/Imagine/impl/QuickControls2ImagineStyleImpl.qmltypes
cp $2/qml/QtQuick/Controls/Fusion/ApplicationWindow.qml $1/qml/QtQuick/Controls/Fusion/ApplicationWindow.qml
cp $2/qml/QtQuick/Controls/Fusion/BusyIndicator.qml $1/qml/QtQuick/Controls/Fusion/BusyIndicator.qml
cp $2/qml/QtQuick/Controls/Fusion/Button.qml $1/qml/QtQuick/Controls/Fusion/Button.qml
cp $2/qml/QtQuick/Controls/Fusion/CheckBox.qml $1/qml/QtQuick/Controls/Fusion/CheckBox.qml
cp $2/qml/QtQuick/Controls/Fusion/CheckDelegate.qml $1/qml/QtQuick/Controls/Fusion/CheckDelegate.qml
cp $2/qml/QtQuick/Controls/Fusion/ComboBox.qml $1/qml/QtQuick/Controls/Fusion/ComboBox.qml
cp $2/qml/QtQuick/Controls/Fusion/DelayButton.qml $1/qml/QtQuick/Controls/Fusion/DelayButton.qml
cp $2/qml/QtQuick/Controls/Fusion/Dial.qml $1/qml/QtQuick/Controls/Fusion/Dial.qml
cp $2/qml/QtQuick/Controls/Fusion/Dialog.qml $1/qml/QtQuick/Controls/Fusion/Dialog.qml
cp $2/qml/QtQuick/Controls/Fusion/DialogButtonBox.qml $1/qml/QtQuick/Controls/Fusion/DialogButtonBox.qml
cp $2/qml/QtQuick/Controls/Fusion/Drawer.qml $1/qml/QtQuick/Controls/Fusion/Drawer.qml
cp $2/qml/QtQuick/Controls/Fusion/Frame.qml $1/qml/QtQuick/Controls/Fusion/Frame.qml
cp $2/qml/QtQuick/Controls/Fusion/GroupBox.qml $1/qml/QtQuick/Controls/Fusion/GroupBox.qml
cp $2/qml/QtQuick/Controls/Fusion/HorizontalHeaderView.qml $1/qml/QtQuick/Controls/Fusion/HorizontalHeaderView.qml
cp $2/qml/QtQuick/Controls/Fusion/ItemDelegate.qml $1/qml/QtQuick/Controls/Fusion/ItemDelegate.qml
cp $2/qml/QtQuick/Controls/Fusion/Label.qml $1/qml/QtQuick/Controls/Fusion/Label.qml
cp $2/qml/QtQuick/Controls/Fusion/Menu.qml $1/qml/QtQuick/Controls/Fusion/Menu.qml
cp $2/qml/QtQuick/Controls/Fusion/MenuBar.qml $1/qml/QtQuick/Controls/Fusion/MenuBar.qml
cp $2/qml/QtQuick/Controls/Fusion/MenuBarItem.qml $1/qml/QtQuick/Controls/Fusion/MenuBarItem.qml
cp $2/qml/QtQuick/Controls/Fusion/MenuItem.qml $1/qml/QtQuick/Controls/Fusion/MenuItem.qml
cp $2/qml/QtQuick/Controls/Fusion/MenuSeparator.qml $1/qml/QtQuick/Controls/Fusion/MenuSeparator.qml
cp $2/qml/QtQuick/Controls/Fusion/Page.qml $1/qml/QtQuick/Controls/Fusion/Page.qml
cp $2/qml/QtQuick/Controls/Fusion/PageIndicator.qml $1/qml/QtQuick/Controls/Fusion/PageIndicator.qml
cp $2/qml/QtQuick/Controls/Fusion/Pane.qml $1/qml/QtQuick/Controls/Fusion/Pane.qml
cp $2/qml/QtQuick/Controls/Fusion/plugins.qmltypes $1/qml/QtQuick/Controls/Fusion/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Fusion/Popup.qml $1/qml/QtQuick/Controls/Fusion/Popup.qml
cp $2/qml/QtQuick/Controls/Fusion/ProgressBar.qml $1/qml/QtQuick/Controls/Fusion/ProgressBar.qml
cp $2/qml/QtQuick/Controls/Fusion/qmldir $1/qml/QtQuick/Controls/Fusion/qmldir
cp $2/qml/QtQuick/Controls/Fusion/libqtquickcontrols2fusionstyleplugin.so $1/qml/QtQuick/Controls/Fusion/libqtquickcontrols2fusionstyleplugin.so
cp $2/qml/QtQuick/Controls/Fusion/RadioButton.qml $1/qml/QtQuick/Controls/Fusion/RadioButton.qml
cp $2/qml/QtQuick/Controls/Fusion/RadioDelegate.qml $1/qml/QtQuick/Controls/Fusion/RadioDelegate.qml
cp $2/qml/QtQuick/Controls/Fusion/RangeSlider.qml $1/qml/QtQuick/Controls/Fusion/RangeSlider.qml
cp $2/qml/QtQuick/Controls/Fusion/RoundButton.qml $1/qml/QtQuick/Controls/Fusion/RoundButton.qml
cp $2/qml/QtQuick/Controls/Fusion/ScrollBar.qml $1/qml/QtQuick/Controls/Fusion/ScrollBar.qml
cp $2/qml/QtQuick/Controls/Fusion/ScrollIndicator.qml $1/qml/QtQuick/Controls/Fusion/ScrollIndicator.qml
cp $2/qml/QtQuick/Controls/Fusion/ScrollView.qml $1/qml/QtQuick/Controls/Fusion/ScrollView.qml
cp $2/qml/QtQuick/Controls/Fusion/SelectionRectangle.qml $1/qml/QtQuick/Controls/Fusion/SelectionRectangle.qml
cp $2/qml/QtQuick/Controls/Fusion/Slider.qml $1/qml/QtQuick/Controls/Fusion/Slider.qml
cp $2/qml/QtQuick/Controls/Fusion/SpinBox.qml $1/qml/QtQuick/Controls/Fusion/SpinBox.qml
cp $2/qml/QtQuick/Controls/Fusion/SplitView.qml $1/qml/QtQuick/Controls/Fusion/SplitView.qml
cp $2/qml/QtQuick/Controls/Fusion/SwipeDelegate.qml $1/qml/QtQuick/Controls/Fusion/SwipeDelegate.qml
cp $2/qml/QtQuick/Controls/Fusion/Switch.qml $1/qml/QtQuick/Controls/Fusion/Switch.qml
cp $2/qml/QtQuick/Controls/Fusion/SwitchDelegate.qml $1/qml/QtQuick/Controls/Fusion/SwitchDelegate.qml
cp $2/qml/QtQuick/Controls/Fusion/TabBar.qml $1/qml/QtQuick/Controls/Fusion/TabBar.qml
cp $2/qml/QtQuick/Controls/Fusion/TabButton.qml $1/qml/QtQuick/Controls/Fusion/TabButton.qml
cp $2/qml/QtQuick/Controls/Fusion/TextArea.qml $1/qml/QtQuick/Controls/Fusion/TextArea.qml
cp $2/qml/QtQuick/Controls/Fusion/TextField.qml $1/qml/QtQuick/Controls/Fusion/TextField.qml
cp $2/qml/QtQuick/Controls/Fusion/ToolBar.qml $1/qml/QtQuick/Controls/Fusion/ToolBar.qml
cp $2/qml/QtQuick/Controls/Fusion/ToolButton.qml $1/qml/QtQuick/Controls/Fusion/ToolButton.qml
cp $2/qml/QtQuick/Controls/Fusion/ToolSeparator.qml $1/qml/QtQuick/Controls/Fusion/ToolSeparator.qml
cp $2/qml/QtQuick/Controls/Fusion/ToolTip.qml $1/qml/QtQuick/Controls/Fusion/ToolTip.qml
cp $2/qml/QtQuick/Controls/Fusion/TreeViewDelegate.qml $1/qml/QtQuick/Controls/Fusion/TreeViewDelegate.qml
cp $2/qml/QtQuick/Controls/Fusion/Tumbler.qml $1/qml/QtQuick/Controls/Fusion/Tumbler.qml
cp $2/qml/QtQuick/Controls/Fusion/VerticalHeaderView.qml $1/qml/QtQuick/Controls/Fusion/VerticalHeaderView.qml
cp $2/qml/QtQuick/Controls/Fusion/impl/ButtonPanel.qml $1/qml/QtQuick/Controls/Fusion/impl/ButtonPanel.qml
cp $2/qml/QtQuick/Controls/Fusion/impl/CheckIndicator.qml $1/qml/QtQuick/Controls/Fusion/impl/CheckIndicator.qml
cp $2/qml/QtQuick/Controls/Fusion/impl/plugins.qmltypes $1/qml/QtQuick/Controls/Fusion/impl/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Fusion/impl/qmldir $1/qml/QtQuick/Controls/Fusion/impl/qmldir
cp $2/qml/QtQuick/Controls/Fusion/impl/libqtquickcontrols2fusionstyleimplplugin.so $1/qml/QtQuick/Controls/Fusion/impl/libqtquickcontrols2fusionstyleimplplugin.so
cp $2/qml/QtQuick/Controls/Fusion/impl/RadioIndicator.qml $1/qml/QtQuick/Controls/Fusion/impl/RadioIndicator.qml
cp $2/qml/QtQuick/Controls/Fusion/impl/SliderGroove.qml $1/qml/QtQuick/Controls/Fusion/impl/SliderGroove.qml
cp $2/qml/QtQuick/Controls/Fusion/impl/SliderHandle.qml $1/qml/QtQuick/Controls/Fusion/impl/SliderHandle.qml
cp $2/qml/QtQuick/Controls/Fusion/impl/SwitchIndicator.qml $1/qml/QtQuick/Controls/Fusion/impl/SwitchIndicator.qml
cp $2/qml/QtQuick/Controls/Basic/AbstractButton.qml $1/qml/QtQuick/Controls/Basic/AbstractButton.qml
cp $2/qml/QtQuick/Controls/Basic/Action.qml $1/qml/QtQuick/Controls/Basic/Action.qml
cp $2/qml/QtQuick/Controls/Basic/ActionGroup.qml $1/qml/QtQuick/Controls/Basic/ActionGroup.qml
cp $2/qml/QtQuick/Controls/Basic/ApplicationWindow.qml $1/qml/QtQuick/Controls/Basic/ApplicationWindow.qml
cp $2/qml/QtQuick/Controls/Basic/BusyIndicator.qml $1/qml/QtQuick/Controls/Basic/BusyIndicator.qml
cp $2/qml/QtQuick/Controls/Basic/Button.qml $1/qml/QtQuick/Controls/Basic/Button.qml
cp $2/qml/QtQuick/Controls/Basic/ButtonGroup.qml $1/qml/QtQuick/Controls/Basic/ButtonGroup.qml
cp $2/qml/QtQuick/Controls/Basic/Calendar.qml $1/qml/QtQuick/Controls/Basic/Calendar.qml
cp $2/qml/QtQuick/Controls/Basic/CalendarModel.qml $1/qml/QtQuick/Controls/Basic/CalendarModel.qml
cp $2/qml/QtQuick/Controls/Basic/CheckBox.qml $1/qml/QtQuick/Controls/Basic/CheckBox.qml
cp $2/qml/QtQuick/Controls/Basic/CheckDelegate.qml $1/qml/QtQuick/Controls/Basic/CheckDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/ComboBox.qml $1/qml/QtQuick/Controls/Basic/ComboBox.qml
cp $2/qml/QtQuick/Controls/Basic/Container.qml $1/qml/QtQuick/Controls/Basic/Container.qml
cp $2/qml/QtQuick/Controls/Basic/Control.qml $1/qml/QtQuick/Controls/Basic/Control.qml
cp $2/qml/QtQuick/Controls/Basic/DayOfWeekRow.qml $1/qml/QtQuick/Controls/Basic/DayOfWeekRow.qml
cp $2/qml/QtQuick/Controls/Basic/DelayButton.qml $1/qml/QtQuick/Controls/Basic/DelayButton.qml
cp $2/qml/QtQuick/Controls/Basic/Dial.qml $1/qml/QtQuick/Controls/Basic/Dial.qml
cp $2/qml/QtQuick/Controls/Basic/Dialog.qml $1/qml/QtQuick/Controls/Basic/Dialog.qml
cp $2/qml/QtQuick/Controls/Basic/DialogButtonBox.qml $1/qml/QtQuick/Controls/Basic/DialogButtonBox.qml
cp $2/qml/QtQuick/Controls/Basic/Drawer.qml $1/qml/QtQuick/Controls/Basic/Drawer.qml
cp $2/qml/QtQuick/Controls/Basic/Frame.qml $1/qml/QtQuick/Controls/Basic/Frame.qml
cp $2/qml/QtQuick/Controls/Basic/GroupBox.qml $1/qml/QtQuick/Controls/Basic/GroupBox.qml
cp $2/qml/QtQuick/Controls/Basic/HorizontalHeaderView.qml $1/qml/QtQuick/Controls/Basic/HorizontalHeaderView.qml
cp $2/qml/QtQuick/Controls/Basic/ItemDelegate.qml $1/qml/QtQuick/Controls/Basic/ItemDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/Label.qml $1/qml/QtQuick/Controls/Basic/Label.qml
cp $2/qml/QtQuick/Controls/Basic/Menu.qml $1/qml/QtQuick/Controls/Basic/Menu.qml
cp $2/qml/QtQuick/Controls/Basic/MenuBar.qml $1/qml/QtQuick/Controls/Basic/MenuBar.qml
cp $2/qml/QtQuick/Controls/Basic/MenuBarItem.qml $1/qml/QtQuick/Controls/Basic/MenuBarItem.qml
cp $2/qml/QtQuick/Controls/Basic/MenuItem.qml $1/qml/QtQuick/Controls/Basic/MenuItem.qml
cp $2/qml/QtQuick/Controls/Basic/MenuSeparator.qml $1/qml/QtQuick/Controls/Basic/MenuSeparator.qml
cp $2/qml/QtQuick/Controls/Basic/MonthGrid.qml $1/qml/QtQuick/Controls/Basic/MonthGrid.qml
cp $2/qml/QtQuick/Controls/Basic/Page.qml $1/qml/QtQuick/Controls/Basic/Page.qml
cp $2/qml/QtQuick/Controls/Basic/PageIndicator.qml $1/qml/QtQuick/Controls/Basic/PageIndicator.qml
cp $2/qml/QtQuick/Controls/Basic/Pane.qml $1/qml/QtQuick/Controls/Basic/Pane.qml
cp $2/qml/QtQuick/Controls/Basic/plugins.qmltypes $1/qml/QtQuick/Controls/Basic/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Basic/Popup.qml $1/qml/QtQuick/Controls/Basic/Popup.qml
cp $2/qml/QtQuick/Controls/Basic/ProgressBar.qml $1/qml/QtQuick/Controls/Basic/ProgressBar.qml
cp $2/qml/QtQuick/Controls/Basic/qmldir $1/qml/QtQuick/Controls/Basic/qmldir
cp $2/qml/QtQuick/Controls/Basic/libqtquickcontrols2basicstyleplugin.so $1/qml/QtQuick/Controls/Basic/libqtquickcontrols2basicstyleplugin.so
cp $2/qml/QtQuick/Controls/Basic/RadioButton.qml $1/qml/QtQuick/Controls/Basic/RadioButton.qml
cp $2/qml/QtQuick/Controls/Basic/RadioDelegate.qml $1/qml/QtQuick/Controls/Basic/RadioDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/RangeSlider.qml $1/qml/QtQuick/Controls/Basic/RangeSlider.qml
cp $2/qml/QtQuick/Controls/Basic/RoundButton.qml $1/qml/QtQuick/Controls/Basic/RoundButton.qml
cp $2/qml/QtQuick/Controls/Basic/ScrollBar.qml $1/qml/QtQuick/Controls/Basic/ScrollBar.qml
cp $2/qml/QtQuick/Controls/Basic/ScrollIndicator.qml $1/qml/QtQuick/Controls/Basic/ScrollIndicator.qml
cp $2/qml/QtQuick/Controls/Basic/ScrollView.qml $1/qml/QtQuick/Controls/Basic/ScrollView.qml
cp $2/qml/QtQuick/Controls/Basic/SelectionRectangle.qml $1/qml/QtQuick/Controls/Basic/SelectionRectangle.qml
cp $2/qml/QtQuick/Controls/Basic/Slider.qml $1/qml/QtQuick/Controls/Basic/Slider.qml
cp $2/qml/QtQuick/Controls/Basic/SpinBox.qml $1/qml/QtQuick/Controls/Basic/SpinBox.qml
cp $2/qml/QtQuick/Controls/Basic/SplitView.qml $1/qml/QtQuick/Controls/Basic/SplitView.qml
cp $2/qml/QtQuick/Controls/Basic/StackView.qml $1/qml/QtQuick/Controls/Basic/StackView.qml
cp $2/qml/QtQuick/Controls/Basic/SwipeDelegate.qml $1/qml/QtQuick/Controls/Basic/SwipeDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/SwipeView.qml $1/qml/QtQuick/Controls/Basic/SwipeView.qml
cp $2/qml/QtQuick/Controls/Basic/Switch.qml $1/qml/QtQuick/Controls/Basic/Switch.qml
cp $2/qml/QtQuick/Controls/Basic/SwitchDelegate.qml $1/qml/QtQuick/Controls/Basic/SwitchDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/TabBar.qml $1/qml/QtQuick/Controls/Basic/TabBar.qml
cp $2/qml/QtQuick/Controls/Basic/TabButton.qml $1/qml/QtQuick/Controls/Basic/TabButton.qml
cp $2/qml/QtQuick/Controls/Basic/TextArea.qml $1/qml/QtQuick/Controls/Basic/TextArea.qml
cp $2/qml/QtQuick/Controls/Basic/TextField.qml $1/qml/QtQuick/Controls/Basic/TextField.qml
cp $2/qml/QtQuick/Controls/Basic/ToolBar.qml $1/qml/QtQuick/Controls/Basic/ToolBar.qml
cp $2/qml/QtQuick/Controls/Basic/ToolButton.qml $1/qml/QtQuick/Controls/Basic/ToolButton.qml
cp $2/qml/QtQuick/Controls/Basic/ToolSeparator.qml $1/qml/QtQuick/Controls/Basic/ToolSeparator.qml
cp $2/qml/QtQuick/Controls/Basic/ToolTip.qml $1/qml/QtQuick/Controls/Basic/ToolTip.qml
cp $2/qml/QtQuick/Controls/Basic/TreeViewDelegate.qml $1/qml/QtQuick/Controls/Basic/TreeViewDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/Tumbler.qml $1/qml/QtQuick/Controls/Basic/Tumbler.qml
cp $2/qml/QtQuick/Controls/Basic/VerticalHeaderView.qml $1/qml/QtQuick/Controls/Basic/VerticalHeaderView.qml
cp $2/qml/QtQuick/Controls/Basic/WeekNumberColumn.qml $1/qml/QtQuick/Controls/Basic/WeekNumberColumn.qml
cp $2/qml/QtQuick/Controls/Basic/impl/plugins.qmltypes $1/qml/QtQuick/Controls/Basic/impl/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Basic/impl/qmldir $1/qml/QtQuick/Controls/Basic/impl/qmldir
cp $2/qml/QtQuick/Controls/Basic/impl/libqtquickcontrols2basicstyleimplplugin.so $1/qml/QtQuick/Controls/Basic/impl/libqtquickcontrols2basicstyleimplplugin.so
cp $2/qml/QtQml/plugins.qmltypes $1/qml/QtQml/plugins.qmltypes
cp $2/qml/QtQml/qmldir $1/qml/QtQml/qmldir
cp $2/qml/QtQml/libqmlplugin.so $1/qml/QtQml/libqmlplugin.so
cp $2/qml/QtQml/XmlListModel/plugins.qmltypes $1/qml/QtQml/XmlListModel/plugins.qmltypes
cp $2/qml/QtQml/XmlListModel/qmldir $1/qml/QtQml/XmlListModel/qmldir
cp $2/qml/QtQml/XmlListModel/libqmlxmllistmodelplugin.so $1/qml/QtQml/XmlListModel/libqmlxmllistmodelplugin.so
cp $2/qml/QtQml/WorkerScript/plugins.qmltypes $1/qml/QtQml/WorkerScript/plugins.qmltypes
cp $2/qml/QtQml/WorkerScript/qmldir $1/qml/QtQml/WorkerScript/qmldir
cp $2/qml/QtQml/WorkerScript/libworkerscriptplugin.so $1/qml/QtQml/WorkerScript/libworkerscriptplugin.so
cp $2/qml/QtQml/Models/libmodelsplugin.so $1/qml/QtQml/Models/libmodelsplugin.so
cp $2/qml/QtQml/Models/plugins.qmltypes $1/qml/QtQml/Models/plugins.qmltypes
cp $2/qml/QtQml/Models/qmldir $1/qml/QtQml/Models/qmldir
cp $2/qml/QtNetwork/plugins.qmltypes $1/qml/QtNetwork/plugins.qmltypes
cp $2/qml/QtNetwork/qmldir $1/qml/QtNetwork/qmldir
cp $2/qml/QtNetwork/libqmlnetworkplugin.so $1/qml/QtNetwork/libqmlnetworkplugin.so
cp $2/qml/QtCore/plugins.qmltypes $1/qml/QtCore/plugins.qmltypes
cp $2/qml/QtCore/qmldir $1/qml/QtCore/qmldir
cp $2/qml/QtCore/libqtqmlcoreplugin.so $1/qml/QtCore/libqtqmlcoreplugin.so
cp $2/qml/Qt/test/controls/qmldir $1/qml/Qt/test/controls/qmldir
cp $2/qml/Qt/test/controls/QuickControlsTestUtilsPrivate.qmltypes $1/qml/Qt/test/controls/QuickControlsTestUtilsPrivate.qmltypes
cp $2/qml/Qt/test/controls/libquickcontrolstestutilsprivateplugin.so $1/qml/Qt/test/controls/libquickcontrolstestutilsprivateplugin.so
cp $2/qml/Qt/labs/wavefrontmesh/plugins.qmltypes $1/qml/Qt/labs/wavefrontmesh/plugins.qmltypes
cp $2/qml/Qt/labs/wavefrontmesh/qmldir $1/qml/Qt/labs/wavefrontmesh/qmldir
cp $2/qml/Qt/labs/wavefrontmesh/libqmlwavefrontmeshplugin.so $1/qml/Qt/labs/wavefrontmesh/libqmlwavefrontmeshplugin.so
cp $2/qml/Qt/labs/sharedimage/plugins.qmltypes $1/qml/Qt/labs/sharedimage/plugins.qmltypes
cp $2/qml/Qt/labs/sharedimage/qmldir $1/qml/Qt/labs/sharedimage/qmldir
cp $2/qml/Qt/labs/sharedimage/libsharedimageplugin.so $1/qml/Qt/labs/sharedimage/libsharedimageplugin.so
cp $2/qml/Qt/labs/settings/plugins.qmltypes $1/qml/Qt/labs/settings/plugins.qmltypes
cp $2/qml/Qt/labs/settings/qmldir $1/qml/Qt/labs/settings/qmldir
cp $2/qml/Qt/labs/settings/libqmlsettingsplugin.so $1/qml/Qt/labs/settings/libqmlsettingsplugin.so
cp $2/qml/Qt/labs/qmlmodels/liblabsmodelsplugin.so $1/qml/Qt/labs/qmlmodels/liblabsmodelsplugin.so
cp $2/qml/Qt/labs/qmlmodels/plugins.qmltypes $1/qml/Qt/labs/qmlmodels/plugins.qmltypes
cp $2/qml/Qt/labs/qmlmodels/qmldir $1/qml/Qt/labs/qmlmodels/qmldir
cp $2/qml/Qt/labs/platform/liblabsplatformplugin.so $1/qml/Qt/labs/platform/liblabsplatformplugin.so
cp $2/qml/Qt/labs/platform/plugins.qmltypes $1/qml/Qt/labs/platform/plugins.qmltypes
cp $2/qml/Qt/labs/platform/qmldir $1/qml/Qt/labs/platform/qmldir
cp $2/qml/Qt/labs/folderlistmodel/plugins.qmltypes $1/qml/Qt/labs/folderlistmodel/plugins.qmltypes
cp $2/qml/Qt/labs/folderlistmodel/qmldir $1/qml/Qt/labs/folderlistmodel/qmldir
cp $2/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.so $1/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.so
cp $2/qml/Qt/labs/animation/liblabsanimationplugin.so $1/qml/Qt/labs/animation/liblabsanimationplugin.so
cp $2/qml/Qt/labs/animation/plugins.qmltypes $1/qml/Qt/labs/animation/plugins.qmltypes
cp $2/qml/Qt/labs/animation/qmldir $1/qml/Qt/labs/animation/qmldir
cp $2/qml/QmlTime/qmldir $1/qml/QmlTime/qmldir
cp $2/qml/QmlTime/qmltime.qmltypes $1/qml/QmlTime/qmltime.qmltypes
cp $2/qml/QML/plugins.qmltypes $1/qml/QML/plugins.qmltypes
cp $2/qml/QML/qmldir $1/qml/QML/qmldir
cp $2/qml/Assets/Downloader/plugins.qmltypes $1/qml/Assets/Downloader/plugins.qmltypes
cp $2/qml/Assets/Downloader/libqmlassetdownloaderplugin.so $1/qml/Assets/Downloader/libqmlassetdownloaderplugin.so
cp $2/qml/Assets/Downloader/qmldir $1/qml/Assets/Downloader/qmldir
