# $1 is tmp path - ${{ github.workspace }}/../__tmp
# $2 is Qt platform path - /home/opc/6.8.0/gcc_arm64

# Core
cp $2/bin/Qt6Core.dll $1/core/Qt6Core.dll
cp $2/bin/Qt6Network.dll $1/core/Qt6Network.dll
cp $2/plugins/platforms/qminimal.dll $1/core/plugins/platforms/qminimal.dll

# Gui
cp $2/bin/Qt6Gui.dll $1/gui/Qt6Gui.dll
cp $2/bin/Qt6OpenGL.dll $1/gui/Qt6OpenGL.dll
cp $2/bin/Qt6Svg.dll $1/gui/Qt6Svg.dll
cp $2/bin/Qt6Widgets.dll $1/gui/Qt6Widgets.dll
cp $2/plugins/iconengines/qsvgicon.dll $1/gui/plugins/iconengines/qsvgicon.dll
cp $2/plugins/imageformats/qgif.dll $1/gui/plugins/imageformats/qgif.dll
cp $2/plugins/imageformats/qico.dll $1/gui/plugins/imageformats/qico.dll
cp $2/plugins/imageformats/qjpeg.dll $1/gui/plugins/imageformats/qjpeg.dll
cp $2/plugins/imageformats/qsvg.dll $1/gui/plugins/imageformats/qsvg.dll
cp $2/plugins/platforms/qoffscreen.dll $1/gui/plugins/platforms/qoffscreen.dll
cp $2/plugins/platforms/qwindows.dll $1/gui/plugins/platforms/qwindows.dll

# QML
cp $2/bin/Qt6Qml.dll $1/qml/Qt6Qml.dll
cp $2/bin/Qt6Quick.dll $1/qml/Qt6Quick.dll
cp $2/bin/Qt6QuickControls2.dll $1/qml/Qt6QuickControls2.dll
cp $2/bin/Qt6QuickTemplates2.dll $1/qml/Qt6QuickTemplates2.dll
cp $2/bin/Qt6QuickWidgets.dll $1/qml/Qt6QuickWidgets.dll

cp $2/bin/Qt6QuickVectorImage.dll $1/qml/Qt6QuickVectorImage.dll
cp $2/bin/Qt6QmlCompiler.dll $1/qml/Qt6QmlCompiler.dll
cp $2/bin/Qt6QmlCore.dll $1/qml/Qt6QmlCore.dll
cp $2/bin/Qt6QuickControls2Basic.dll $1/qml/Qt6QuickControls2Basic.dll
cp $2/bin/Qt6QuickControls2Impl.dll $1/qml/Qt6QuickControls2Impl.dll
cp $2/bin/Qt6QuickDialogs2.dll $1/qml/Qt6QuickDialogs2.dll
cp $2/bin/Qt6QuickDialogs2QuickImpl.dll $1/qml/Qt6QuickDialogs2QuickImpl.dll
cp $2/bin/Qt6QuickDialogs2Utils.dll $1/qml/Qt6QuickDialogs2Utils.dll
cp $2/bin/Qt6QuickEffects.dll $1/qml/Qt6QuickEffects.dll
cp $2/bin/Qt6QuickLayouts.dll $1/qml/Qt6QuickLayouts.dll
cp $2/bin/Qt6QuickParticles.dll $1/qml/Qt6QuickParticles.dll
cp $2/bin/Qt6QuickShapes.dll $1/qml/Qt6QuickShapes.dll
cp $2/bin/Qt6QmlWorkerScript.dll $1/qml/Qt6QmlWorkerScript.dll
cp $2/bin/Qt6QmlModels.dll $1/qml/Qt6QmlModels.dll

cp $2/plugins/qmltooling/qmldbg_debugger.dll $1/qml/plugins/qmltooling/qmldbg_debugger.dll
cp $2/plugins/qmltooling/qmldbg_inspector.dll $1/qml/plugins/qmltooling/qmldbg_inspector.dll
cp $2/plugins/qmltooling/qmldbg_local.dll $1/qml/plugins/qmltooling/qmldbg_local.dll
cp $2/plugins/qmltooling/qmldbg_messages.dll $1/qml/plugins/qmltooling/qmldbg_messages.dll
cp $2/plugins/qmltooling/qmldbg_native.dll $1/qml/plugins/qmltooling/qmldbg_native.dll
cp $2/plugins/qmltooling/qmldbg_nativedebugger.dll $1/qml/plugins/qmltooling/qmldbg_nativedebugger.dll
cp $2/plugins/qmltooling/qmldbg_preview.dll $1/qml/plugins/qmltooling/qmldbg_preview.dll
cp $2/plugins/qmltooling/qmldbg_profiler.dll $1/qml/plugins/qmltooling/qmldbg_profiler.dll
cp $2/plugins/qmltooling/qmldbg_quickprofiler.dll $1/qml/plugins/qmltooling/qmldbg_quickprofiler.dll
cp $2/plugins/qmltooling/qmldbg_server.dll $1/qml/plugins/qmltooling/qmldbg_server.dll
cp $2/plugins/qmltooling/qmldbg_tcp.dll $1/qml/plugins/qmltooling/qmldbg_tcp.dll

cp $2/qml/builtins.qmltypes $1/qml/qml/builtins.qmltypes
cp $2/qml/jsroot.qmltypes $1/qml/qml/jsroot.qmltypes
cp $2/qml/QtTest/plugins.qmltypes $1/qml/qml/QtTest/plugins.qmltypes
cp $2/qml/QtTest/qmldir $1/qml/qml/QtTest/qmldir
cp $2/qml/QtTest/quicktestplugin.dll $1/qml/qml/QtTest/quicktestplugin.dll
cp $2/qml/QtTest/SignalSpy.qml $1/qml/qml/QtTest/SignalSpy.qml
cp $2/qml/QtTest/TestCase.qml $1/qml/qml/QtTest/TestCase.qml
cp $2/qml/QtTest/testlogger.js $1/qml/qml/QtTest/testlogger.js
cp $2/qml/QtTest/TestSchedule.qml $1/qml/qml/QtTest/TestSchedule.qml
cp $2/qml/QtQuick/plugins.qmltypes $1/qml/qml/QtQuick/plugins.qmltypes
cp $2/qml/QtQuick/qmldir $1/qml/qml/QtQuick/qmldir
cp $2/qml/QtQuick/qtquick2plugin.dll $1/qml/qml/QtQuick/qtquick2plugin.dll
cp $2/qml/QtQuick/Window/qmldir $1/qml/qml/QtQuick/Window/qmldir
cp $2/qml/QtQuick/Window/quickwindow.qmltypes $1/qml/qml/QtQuick/Window/quickwindow.qmltypes
cp $2/qml/QtQuick/Window/quickwindowplugin.dll $1/qml/qml/QtQuick/Window/quickwindowplugin.dll
cp $2/qml/QtQuick/VectorImage/plugins.qmltypes $1/qml/qml/QtQuick/VectorImage/plugins.qmltypes
cp $2/qml/QtQuick/VectorImage/qmldir $1/qml/qml/QtQuick/VectorImage/qmldir
cp $2/qml/QtQuick/VectorImage/qquickvectorimageplugin.dll $1/qml/qml/QtQuick/VectorImage/qquickvectorimageplugin.dll
cp $2/qml/QtQuick/tooling/Component.qml $1/qml/qml/QtQuick/tooling/Component.qml
cp $2/qml/QtQuick/tooling/Enum.qml $1/qml/qml/QtQuick/tooling/Enum.qml
cp $2/qml/QtQuick/tooling/Member.qml $1/qml/qml/QtQuick/tooling/Member.qml
cp $2/qml/QtQuick/tooling/Method.qml $1/qml/qml/QtQuick/tooling/Method.qml
cp $2/qml/QtQuick/tooling/Module.qml $1/qml/qml/QtQuick/tooling/Module.qml
cp $2/qml/QtQuick/tooling/Parameter.qml $1/qml/qml/QtQuick/tooling/Parameter.qml
cp $2/qml/QtQuick/tooling/Property.qml $1/qml/qml/QtQuick/tooling/Property.qml
cp $2/qml/QtQuick/tooling/qmldir $1/qml/qml/QtQuick/tooling/qmldir
cp $2/qml/QtQuick/tooling/quicktooling.qmltypes $1/qml/qml/QtQuick/tooling/quicktooling.qmltypes
cp $2/qml/QtQuick/tooling/quicktoolingplugin.dll $1/qml/qml/QtQuick/tooling/quicktoolingplugin.dll
cp $2/qml/QtQuick/tooling/Signal.qml $1/qml/qml/QtQuick/tooling/Signal.qml
cp $2/qml/QtQuick/Templates/plugins.qmltypes $1/qml/qml/QtQuick/Templates/plugins.qmltypes
cp $2/qml/QtQuick/Templates/qmldir $1/qml/qml/QtQuick/Templates/qmldir
cp $2/qml/QtQuick/Templates/qtquicktemplates2plugin.dll $1/qml/qml/QtQuick/Templates/qtquicktemplates2plugin.dll
cp $2/qml/QtQuick/Shapes/plugins.qmltypes $1/qml/qml/QtQuick/Shapes/plugins.qmltypes
cp $2/qml/QtQuick/Shapes/qmldir $1/qml/qml/QtQuick/Shapes/qmldir
cp $2/qml/QtQuick/Shapes/qmlshapesplugin.dll $1/qml/qml/QtQuick/Shapes/qmlshapesplugin.dll
cp $2/qml/QtQuick/Particles/particlesplugin.dll $1/qml/qml/QtQuick/Particles/particlesplugin.dll
cp $2/qml/QtQuick/Particles/plugins.qmltypes $1/qml/qml/QtQuick/Particles/plugins.qmltypes
cp $2/qml/QtQuick/Particles/qmldir $1/qml/qml/QtQuick/Particles/qmldir
cp $2/qml/QtQuick/NativeStyle/plugins.qmltypes $1/qml/qml/QtQuick/NativeStyle/plugins.qmltypes
cp $2/qml/QtQuick/NativeStyle/qmldir $1/qml/qml/QtQuick/NativeStyle/qmldir
cp $2/qml/QtQuick/NativeStyle/qtquickcontrols2nativestyleplugin.dll $1/qml/qml/QtQuick/NativeStyle/qtquickcontrols2nativestyleplugin.dll
cp $2/qml/QtQuick/NativeStyle/util/qmldir $1/qml/qml/QtQuick/NativeStyle/util/qmldir
cp $2/qml/QtQuick/NativeStyle/util/WindowsFocusFrame.qml $1/qml/qml/QtQuick/NativeStyle/util/WindowsFocusFrame.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultButton.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultButton.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultCheckBox.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultCheckBox.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultComboBox.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultComboBox.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultDial.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultDial.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultFrame.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultFrame.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultGroupBox.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultGroupBox.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultItemDelegate.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultItemDelegate.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultItemDelegateIconLabel.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultItemDelegateIconLabel.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultProgressBar.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultProgressBar.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultRadioButton.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultRadioButton.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultRadioDelegate.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultRadioDelegate.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultScrollBar.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultScrollBar.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultSlider.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultSlider.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultSpinBox.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultSpinBox.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultTextArea.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultTextArea.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultTextField.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultTextField.qml
cp $2/qml/QtQuick/NativeStyle/controls/DefaultTreeViewDelegate.qml $1/qml/qml/QtQuick/NativeStyle/controls/DefaultTreeViewDelegate.qml
cp $2/qml/QtQuick/NativeStyle/controls/qmldir $1/qml/qml/QtQuick/NativeStyle/controls/qmldir
cp $2/qml/QtQuick/LocalStorage/plugins.qmltypes $1/qml/qml/QtQuick/LocalStorage/plugins.qmltypes
cp $2/qml/QtQuick/LocalStorage/qmldir $1/qml/qml/QtQuick/LocalStorage/qmldir
cp $2/qml/QtQuick/LocalStorage/qmllocalstorageplugin.dll $1/qml/qml/QtQuick/LocalStorage/qmllocalstorageplugin.dll
cp $2/qml/QtQuick/Layouts/plugins.qmltypes $1/qml/qml/QtQuick/Layouts/plugins.qmltypes
cp $2/qml/QtQuick/Layouts/qmldir $1/qml/qml/QtQuick/Layouts/qmldir
cp $2/qml/QtQuick/Layouts/qquicklayoutsplugin.dll $1/qml/qml/QtQuick/Layouts/qquicklayoutsplugin.dll
cp $2/qml/QtQuick/Effects/effectsplugin.dll $1/qml/qml/QtQuick/Effects/effectsplugin.dll
cp $2/qml/QtQuick/Effects/plugins.qmltypes $1/qml/qml/QtQuick/Effects/plugins.qmltypes
cp $2/qml/QtQuick/Effects/qmldir $1/qml/qml/QtQuick/Effects/qmldir
cp $2/qml/QtQuick/Dialogs/plugins.qmltypes $1/qml/qml/QtQuick/Dialogs/plugins.qmltypes
cp $2/qml/QtQuick/Dialogs/qmldir $1/qml/qml/QtQuick/Dialogs/qmldir
cp $2/qml/QtQuick/Dialogs/qtquickdialogsplugin.dll $1/qml/qml/QtQuick/Dialogs/qtquickdialogsplugin.dll
cp $2/qml/QtQuick/Dialogs/quickimpl/plugins.qmltypes $1/qml/qml/QtQuick/Dialogs/quickimpl/plugins.qmltypes
cp $2/qml/QtQuick/Dialogs/quickimpl/qmldir $1/qml/qml/QtQuick/Dialogs/quickimpl/qmldir
cp $2/qml/QtQuick/Dialogs/quickimpl/qtquickdialogs2quickimplplugin.dll $1/qml/qml/QtQuick/Dialogs/quickimpl/qtquickdialogs2quickimplplugin.dll
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/ColorDialog.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/ColorDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/ColorInputs.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/ColorInputs.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FileDialog.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/FileDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FileDialogDelegate.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/FileDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FileDialogDelegateLabel.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/FileDialogDelegateLabel.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FolderBreadcrumbBar.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/FolderBreadcrumbBar.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialog.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialogDelegate.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialogDelegate.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialogDelegateLabel.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/FolderDialogDelegateLabel.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FontDialog.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/FontDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/FontDialogContent.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/FontDialogContent.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/HueGradient.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/HueGradient.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/MessageDialog.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/MessageDialog.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/PickerHandle.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/PickerHandle.qml
cp $2/qml/QtQuick/Dialogs/quickimpl/qml/SaturationLightnessPicker.qml $1/qml/qml/QtQuick/Dialogs/quickimpl/qml/SaturationLightnessPicker.qml
cp $2/qml/QtQuick/Controls/plugins.qmltypes $1/qml/qml/QtQuick/Controls/plugins.qmltypes
cp $2/qml/QtQuick/Controls/qmldir $1/qml/qml/QtQuick/Controls/qmldir
cp $2/qml/QtQuick/Controls/qtquickcontrols2plugin.dll $1/qml/qml/QtQuick/Controls/qtquickcontrols2plugin.dll
cp $2/qml/QtQuick/Controls/impl/plugins.qmltypes $1/qml/qml/QtQuick/Controls/impl/plugins.qmltypes
cp $2/qml/QtQuick/Controls/impl/qmldir $1/qml/qml/QtQuick/Controls/impl/qmldir
cp $2/qml/QtQuick/Controls/impl/qtquickcontrols2implplugin.dll $1/qml/qml/QtQuick/Controls/impl/qtquickcontrols2implplugin.dll
cp $2/qml/QtQuick/Controls/Basic/AbstractButton.qml $1/qml/qml/QtQuick/Controls/Basic/AbstractButton.qml
cp $2/qml/QtQuick/Controls/Basic/Action.qml $1/qml/qml/QtQuick/Controls/Basic/Action.qml
cp $2/qml/QtQuick/Controls/Basic/ActionGroup.qml $1/qml/qml/QtQuick/Controls/Basic/ActionGroup.qml
cp $2/qml/QtQuick/Controls/Basic/ApplicationWindow.qml $1/qml/qml/QtQuick/Controls/Basic/ApplicationWindow.qml
cp $2/qml/QtQuick/Controls/Basic/BusyIndicator.qml $1/qml/qml/QtQuick/Controls/Basic/BusyIndicator.qml
cp $2/qml/QtQuick/Controls/Basic/Button.qml $1/qml/qml/QtQuick/Controls/Basic/Button.qml
cp $2/qml/QtQuick/Controls/Basic/ButtonGroup.qml $1/qml/qml/QtQuick/Controls/Basic/ButtonGroup.qml
cp $2/qml/QtQuick/Controls/Basic/Calendar.qml $1/qml/qml/QtQuick/Controls/Basic/Calendar.qml
cp $2/qml/QtQuick/Controls/Basic/CalendarModel.qml $1/qml/qml/QtQuick/Controls/Basic/CalendarModel.qml
cp $2/qml/QtQuick/Controls/Basic/CheckBox.qml $1/qml/qml/QtQuick/Controls/Basic/CheckBox.qml
cp $2/qml/QtQuick/Controls/Basic/CheckDelegate.qml $1/qml/qml/QtQuick/Controls/Basic/CheckDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/ComboBox.qml $1/qml/qml/QtQuick/Controls/Basic/ComboBox.qml
cp $2/qml/QtQuick/Controls/Basic/Container.qml $1/qml/qml/QtQuick/Controls/Basic/Container.qml
cp $2/qml/QtQuick/Controls/Basic/Control.qml $1/qml/qml/QtQuick/Controls/Basic/Control.qml
cp $2/qml/QtQuick/Controls/Basic/DayOfWeekRow.qml $1/qml/qml/QtQuick/Controls/Basic/DayOfWeekRow.qml
cp $2/qml/QtQuick/Controls/Basic/DelayButton.qml $1/qml/qml/QtQuick/Controls/Basic/DelayButton.qml
cp $2/qml/QtQuick/Controls/Basic/Dial.qml $1/qml/qml/QtQuick/Controls/Basic/Dial.qml
cp $2/qml/QtQuick/Controls/Basic/Dialog.qml $1/qml/qml/QtQuick/Controls/Basic/Dialog.qml
cp $2/qml/QtQuick/Controls/Basic/DialogButtonBox.qml $1/qml/qml/QtQuick/Controls/Basic/DialogButtonBox.qml
cp $2/qml/QtQuick/Controls/Basic/Drawer.qml $1/qml/qml/QtQuick/Controls/Basic/Drawer.qml
cp $2/qml/QtQuick/Controls/Basic/Frame.qml $1/qml/qml/QtQuick/Controls/Basic/Frame.qml
cp $2/qml/QtQuick/Controls/Basic/GroupBox.qml $1/qml/qml/QtQuick/Controls/Basic/GroupBox.qml
cp $2/qml/QtQuick/Controls/Basic/HorizontalHeaderView.qml $1/qml/qml/QtQuick/Controls/Basic/HorizontalHeaderView.qml
cp $2/qml/QtQuick/Controls/Basic/ItemDelegate.qml $1/qml/qml/QtQuick/Controls/Basic/ItemDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/Label.qml $1/qml/qml/QtQuick/Controls/Basic/Label.qml
cp $2/qml/QtQuick/Controls/Basic/Menu.qml $1/qml/qml/QtQuick/Controls/Basic/Menu.qml
cp $2/qml/QtQuick/Controls/Basic/MenuBar.qml $1/qml/qml/QtQuick/Controls/Basic/MenuBar.qml
cp $2/qml/QtQuick/Controls/Basic/MenuBarItem.qml $1/qml/qml/QtQuick/Controls/Basic/MenuBarItem.qml
cp $2/qml/QtQuick/Controls/Basic/MenuItem.qml $1/qml/qml/QtQuick/Controls/Basic/MenuItem.qml
cp $2/qml/QtQuick/Controls/Basic/MenuSeparator.qml $1/qml/qml/QtQuick/Controls/Basic/MenuSeparator.qml
cp $2/qml/QtQuick/Controls/Basic/MonthGrid.qml $1/qml/qml/QtQuick/Controls/Basic/MonthGrid.qml
cp $2/qml/QtQuick/Controls/Basic/Page.qml $1/qml/qml/QtQuick/Controls/Basic/Page.qml
cp $2/qml/QtQuick/Controls/Basic/PageIndicator.qml $1/qml/qml/QtQuick/Controls/Basic/PageIndicator.qml
cp $2/qml/QtQuick/Controls/Basic/Pane.qml $1/qml/qml/QtQuick/Controls/Basic/Pane.qml
cp $2/qml/QtQuick/Controls/Basic/plugins.qmltypes $1/qml/qml/QtQuick/Controls/Basic/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Basic/Popup.qml $1/qml/qml/QtQuick/Controls/Basic/Popup.qml
cp $2/qml/QtQuick/Controls/Basic/ProgressBar.qml $1/qml/qml/QtQuick/Controls/Basic/ProgressBar.qml
cp $2/qml/QtQuick/Controls/Basic/qmldir $1/qml/qml/QtQuick/Controls/Basic/qmldir
cp $2/qml/QtQuick/Controls/Basic/qtquickcontrols2basicstyleplugin.dll $1/qml/qml/QtQuick/Controls/Basic/qtquickcontrols2basicstyleplugin.dll
cp $2/qml/QtQuick/Controls/Basic/RadioButton.qml $1/qml/qml/QtQuick/Controls/Basic/RadioButton.qml
cp $2/qml/QtQuick/Controls/Basic/RadioDelegate.qml $1/qml/qml/QtQuick/Controls/Basic/RadioDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/RangeSlider.qml $1/qml/qml/QtQuick/Controls/Basic/RangeSlider.qml
cp $2/qml/QtQuick/Controls/Basic/RoundButton.qml $1/qml/qml/QtQuick/Controls/Basic/RoundButton.qml
cp $2/qml/QtQuick/Controls/Basic/ScrollBar.qml $1/qml/qml/QtQuick/Controls/Basic/ScrollBar.qml
cp $2/qml/QtQuick/Controls/Basic/ScrollIndicator.qml $1/qml/qml/QtQuick/Controls/Basic/ScrollIndicator.qml
cp $2/qml/QtQuick/Controls/Basic/ScrollView.qml $1/qml/qml/QtQuick/Controls/Basic/ScrollView.qml
cp $2/qml/QtQuick/Controls/Basic/SelectionRectangle.qml $1/qml/qml/QtQuick/Controls/Basic/SelectionRectangle.qml
cp $2/qml/QtQuick/Controls/Basic/Slider.qml $1/qml/qml/QtQuick/Controls/Basic/Slider.qml
cp $2/qml/QtQuick/Controls/Basic/SpinBox.qml $1/qml/qml/QtQuick/Controls/Basic/SpinBox.qml
cp $2/qml/QtQuick/Controls/Basic/SplitView.qml $1/qml/qml/QtQuick/Controls/Basic/SplitView.qml
cp $2/qml/QtQuick/Controls/Basic/StackView.qml $1/qml/qml/QtQuick/Controls/Basic/StackView.qml
cp $2/qml/QtQuick/Controls/Basic/SwipeDelegate.qml $1/qml/qml/QtQuick/Controls/Basic/SwipeDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/SwipeView.qml $1/qml/qml/QtQuick/Controls/Basic/SwipeView.qml
cp $2/qml/QtQuick/Controls/Basic/Switch.qml $1/qml/qml/QtQuick/Controls/Basic/Switch.qml
cp $2/qml/QtQuick/Controls/Basic/SwitchDelegate.qml $1/qml/qml/QtQuick/Controls/Basic/SwitchDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/TabBar.qml $1/qml/qml/QtQuick/Controls/Basic/TabBar.qml
cp $2/qml/QtQuick/Controls/Basic/TabButton.qml $1/qml/qml/QtQuick/Controls/Basic/TabButton.qml
cp $2/qml/QtQuick/Controls/Basic/TextArea.qml $1/qml/qml/QtQuick/Controls/Basic/TextArea.qml
cp $2/qml/QtQuick/Controls/Basic/TextField.qml $1/qml/qml/QtQuick/Controls/Basic/TextField.qml
cp $2/qml/QtQuick/Controls/Basic/ToolBar.qml $1/qml/qml/QtQuick/Controls/Basic/ToolBar.qml
cp $2/qml/QtQuick/Controls/Basic/ToolButton.qml $1/qml/qml/QtQuick/Controls/Basic/ToolButton.qml
cp $2/qml/QtQuick/Controls/Basic/ToolSeparator.qml $1/qml/qml/QtQuick/Controls/Basic/ToolSeparator.qml
cp $2/qml/QtQuick/Controls/Basic/ToolTip.qml $1/qml/qml/QtQuick/Controls/Basic/ToolTip.qml
cp $2/qml/QtQuick/Controls/Basic/TreeViewDelegate.qml $1/qml/qml/QtQuick/Controls/Basic/TreeViewDelegate.qml
cp $2/qml/QtQuick/Controls/Basic/Tumbler.qml $1/qml/qml/QtQuick/Controls/Basic/Tumbler.qml
cp $2/qml/QtQuick/Controls/Basic/VerticalHeaderView.qml $1/qml/qml/QtQuick/Controls/Basic/VerticalHeaderView.qml
cp $2/qml/QtQuick/Controls/Basic/WeekNumberColumn.qml $1/qml/qml/QtQuick/Controls/Basic/WeekNumberColumn.qml
cp $2/qml/QtQuick/Controls/Basic/impl/plugins.qmltypes $1/qml/qml/QtQuick/Controls/Basic/impl/plugins.qmltypes
cp $2/qml/QtQuick/Controls/Basic/impl/qmldir $1/qml/qml/QtQuick/Controls/Basic/impl/qmldir
cp $2/qml/QtQuick/Controls/Basic/impl/qtquickcontrols2basicstyleimplplugin.dll $1/qml/qml/QtQuick/Controls/Basic/impl/qtquickcontrols2basicstyleimplplugin.dll
cp $2/qml/QtQml/plugins.qmltypes $1/qml/qml/QtQml/plugins.qmltypes
cp $2/qml/QtQml/qmldir $1/qml/qml/QtQml/qmldir
cp $2/qml/QtQml/qmlplugin.dll $1/qml/qml/QtQml/qmlplugin.dll
cp $2/qml/QtQml/XmlListModel/plugins.qmltypes $1/qml/qml/QtQml/XmlListModel/plugins.qmltypes
cp $2/qml/QtQml/XmlListModel/qmldir $1/qml/qml/QtQml/XmlListModel/qmldir
cp $2/qml/QtQml/XmlListModel/qmlxmllistmodelplugin.dll $1/qml/qml/QtQml/XmlListModel/qmlxmllistmodelplugin.dll
cp $2/qml/QtQml/WorkerScript/plugins.qmltypes $1/qml/qml/QtQml/WorkerScript/plugins.qmltypes
cp $2/qml/QtQml/WorkerScript/qmldir $1/qml/qml/QtQml/WorkerScript/qmldir
cp $2/qml/QtQml/WorkerScript/workerscriptplugin.dll $1/qml/qml/QtQml/WorkerScript/workerscriptplugin.dll
cp $2/qml/QtQml/Models/modelsplugin.dll $1/qml/qml/QtQml/Models/modelsplugin.dll
cp $2/qml/QtQml/Models/plugins.qmltypes $1/qml/qml/QtQml/Models/plugins.qmltypes
cp $2/qml/QtQml/Models/qmldir $1/qml/qml/QtQml/Models/qmldir
cp $2/qml/QtNetwork/plugins.qmltypes $1/qml/qml/QtNetwork/plugins.qmltypes
cp $2/qml/QtNetwork/qmldir $1/qml/qml/QtNetwork/qmldir
cp $2/qml/QtNetwork/qmlnetworkplugin.dll $1/qml/qml/QtNetwork/qmlnetworkplugin.dll
cp $2/qml/QtCore/plugins.qmltypes $1/qml/qml/QtCore/plugins.qmltypes
cp $2/qml/QtCore/qmldir $1/qml/qml/QtCore/qmldir
cp $2/qml/QtCore/qtqmlcoreplugin.dll $1/qml/qml/QtCore/qtqmlcoreplugin.dll
cp $2/qml/Qt/test/controls/qmldir $1/qml/qml/Qt/test/controls/qmldir
cp $2/qml/Qt/test/controls/QuickControlsTestUtilsPrivate.qmltypes $1/qml/qml/Qt/test/controls/QuickControlsTestUtilsPrivate.qmltypes
cp $2/qml/Qt/test/controls/quickcontrolstestutilsprivateplugin.dll $1/qml/qml/Qt/test/controls/quickcontrolstestutilsprivateplugin.dll
cp $2/qml/QmlTime/qmldir $1/qml/qml/QmlTime/qmldir
cp $2/qml/QmlTime/qmltime.qmltypes $1/qml/qml/QmlTime/qmltime.qmltypes
cp $2/qml/QML/plugins.qmltypes $1/qml/qml/QML/plugins.qmltypes
cp $2/qml/QML/qmldir $1/qml/qml/QML/qmldir
cp $2/qml/Assets/Downloader/plugins.qmltypes $1/qml/qml/Assets/Downloader/plugins.qmltypes
cp $2/qml/Assets/Downloader/qmlassetdownloaderplugin.dll $1/qml/qml/Assets/Downloader/qmlassetdownloaderplugin.dll
cp $2/qml/Assets/Downloader/qmldir $1/qml/qml/Assets/Downloader/qmldir
